version: '3.8'

volumes:
  mysqldb_vol:

services:
  mysqlsrv:
    image: mysql:8
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1089"
      MYSQL_PASSWORD: "1089"
      MYSQL_DATABASE: "note"
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_vol:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8082:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge