CREATE TABLE title (
	id INT NOT NULL AUTO_INCREMENT,
	name varchar(255) NOT NULL,
	code VARCHAR(20) NOT NULL,
	type VARCHAR(20) NOT NULL,
	PRIMARY KEY ( id )
);

insert into title (name, code,type) values ('3R PETROLEUM ON','RRRP3','ACTION');
insert into title (name, code,type) values ('3TENTOS ON','TTEN3','ACTION');
insert into title (name, code,type) values ('ABC BRASIL PN','ABCB4','ACTION');
insert into title (name, code,type) values ('ADOBE INC DRN','ADBE34','ACTION');
insert into title (name, code,type) values ('ADVANCED MIC DRN','A1MD34','ACTION');
insert into title (name, code,type) values ('AERIS ON','AERI3','ACTION');
insert into title (name, code,type) values ('AES BRASIL ON','AESB3','ACTION');
insert into title (name, code,type) values ('AGROGALAXY ON','AGXY3','ACTION');
insert into title (name, code,type) values ('AIRBNB DRN','AIRB34','ACTION');
insert into title (name, code,type) values ('ALIANSCSONAE ON','ALSO3','ACTION');
insert into title (name, code,type) values ('ALIBABAGR DRN','BABA34','ACTION');
insert into title (name, code,type) values ('ALLIAR ON','AALR3','ACTION');
insert into title (name, code,type) values ('ALLIED ON','ALLD3','ACTION');
insert into title (name, code,type) values ('ALPARGATAS PN','ALPA4','ACTION');
insert into title (name, code,type) values ('ALPHABET DRN A','GOGL34','ACTION');
insert into title (name, code,type) values ('ALUPAR UNT','ALUP11','ACTION');
insert into title (name, code,type) values ('AMAZON DRN','AMZO34','ACTION');
insert into title (name, code,type) values ('AMBEV S/A ON','ABEV3','ACTION');
insert into title (name, code,type) values ('AMBIPAR ON','AMBP3','ACTION');
insert into title (name, code,type) values ('AMERICAN AIR DRN','AALL34','ACTION');
insert into title (name, code,type) values ('AMERICANAS ON','AMER3','ACTION');
insert into title (name, code,type) values ('ANIMA ON','ANIM3','ACTION');
insert into title (name, code,type) values ('APPLE DRN','AAPL34','ACTION');
insert into title (name, code,type) values ('AREZZO CO ON','ARZZ3','ACTION');
insert into title (name, code,type) values ('ARMAC ON','ARML3','ACTION');
insert into title (name, code,type) values ('ASSAI ON','ASAI3','ACTION');
insert into title (name, code,type) values ('AURA 360 DR3','AURA33','ACTION');
insert into title (name, code,type) values ('AZUL PN','AZUL4','ACTION');
insert into title (name, code,type) values ('B3 ON','B3SA3','ACTION');
insert into title (name, code,type) values ('BANCO BMG PN','BMGB4','ACTION');
insert into title (name, code,type) values ('BANCO INTER ON EJ','BIDI3','ACTION');
insert into title (name, code,type) values ('BANCO INTER PN EJ','BIDI4','ACTION');
insert into title (name, code,type) values ('BANCO INTER UNT EJ','BIDI11','ACTION');
insert into title (name, code,type) values ('BANCO PAN PN','BPAN4','ACTION');
insert into title (name, code,type) values ('BANK AMERICA DRN ED','BOAC34','ACTION');
insert into title (name, code,type) values ('BANRISUL PNB','BRSR6','ACTION');
insert into title (name, code,type) values ('BBSEGURIDADE ON','BBSE3','ACTION');
insert into title (name, code,type) values ('BEMOBI TECH ON','BMOB3','ACTION');
insert into title (name, code,type) values ('BERKSHIRE DRN','BERK34','ACTION');
insert into title (name, code,type) values ('BIONTECH SE DRN','B1NT34','ACTION');
insert into title (name, code,type) values ('BITCOIN HASH CI','BITH11','ACTION');
insert into title (name, code,type) values ('BK BRASIL ON','BKBR3','ACTION');
insert into title (name, code,type) values ('BLAU ON','BLAU3','ACTION');
insert into title (name, code,type) values ('BOA SAFRA ON','SOJA3','ACTION');
insert into title (name, code,type) values ('BOA VISTA ON','BOAS3','ACTION');
insert into title (name, code,type) values ('BOOKING DRN','BKNG34','ACTION');
insert into title (name, code,type) values ('BR BROKERS ON','BBRK3','ACTION');
insert into title (name, code,type) values ('BR MALLS PAR ON','BRML3','ACTION');
insert into title (name, code,type) values ('BR PARTNERS UNT','BRBI11','ACTION');
insert into title (name, code,type) values ('BR PROPERT ON','BRPR3','ACTION');
insert into title (name, code,type) values ('BRADESCO ON EJ','BBDC3','ACTION');
insert into title (name, code,type) values ('BRADESCO PN EJ','BBDC4','ACTION');
insert into title (name, code,type) values ('BRADESPAR ON','BRAP3','ACTION');
insert into title (name, code,type) values ('BRADESPAR PN','BRAP4','ACTION');
insert into title (name, code,type) values ('BRASIL ON EX','BBAS3','ACTION');
insert into title (name, code,type) values ('BRASILAGRO ON','AGRO3','ACTION');
insert into title (name, code,type) values ('BRASKEM PNA','BRKM5','ACTION');
insert into title (name, code,type) values ('BRF SA ON','BRFS3','ACTION');
insert into title (name, code,type) values ('BRISANET ON','BRIT3','ACTION');
insert into title (name, code,type) values ('BTGP BANCO UNT','BPAC11','ACTION');
insert into title (name, code,type) values ('CAIXA SEGURI ON','CXSE3','ACTION');
insert into title (name, code,type) values ('CAMIL ON EJ','CAML3','ACTION');
insert into title (name, code,type) values ('CARREFOUR BR ON','CRFB3','ACTION');
insert into title (name, code,type) values ('CBA ON','CBAV3','ACTION');
insert into title (name, code,type) values ('CCR SA ON','CCRO3','ACTION');
insert into title (name, code,type) values ('CEA MODAS ON','CEAB3','ACTION');
insert into title (name, code,type) values ('CEMIG ON','CMIG3','ACTION');
insert into title (name, code,type) values ('CEMIG PN','CMIG4','ACTION');
insert into title (name, code,type) values ('CESP PNB','CESP6','ACTION');
insert into title (name, code,type) values ('CHEVRON DRN','CHVX34','ACTION');
insert into title (name, code,type) values ('CIELO ON','CIEL3','ACTION');
insert into title (name, code,type) values ('CLEARSALE ON','CLSA3','ACTION');
insert into title (name, code,type) values ('COCA COLA DRN','COCA34','ACTION');
insert into title (name, code,type) values ('COGNA ON ON','COGN3','ACTION');
insert into title (name, code,type) values ('COMCAST DRN','CMCS34','ACTION');
insert into title (name, code,type) values ('COPASA ON','CSMG3','ACTION');
insert into title (name, code,type) values ('COPEL ON','CPLE3','ACTION');
insert into title (name, code,type) values ('COPEL PNB','CPLE6','ACTION');
insert into title (name, code,type) values ('COPEL UNT','CPLE11','ACTION');
insert into title (name, code,type) values ('COREMSCI EUR DRN','BIEU39','ACTION');
insert into title (name, code,type) values ('COSAN ON','CSAN3','ACTION');
insert into title (name, code,type) values ('COSTCO DRN','COWC34','ACTION');
insert into title (name, code,type) values ('CPFL ENERGIA ON','CPFE3','ACTION');
insert into title (name, code,type) values ('CRUZEIRO EDU ON','CSED3','ACTION');
insert into title (name, code,type) values ('CSNMINERACAO ON','CMIN3','ACTION');
insert into title (name, code,type) values ('CSU CARDSYST ON','CARD3','ACTION');
insert into title (name, code,type) values ('CURY S/A ON','CURY3','ACTION');
insert into title (name, code,type) values ('CVC BRASIL ON','CVCB3','ACTION');
insert into title (name, code,type) values ('CYRELA REALT ON','CYRE3','ACTION');
insert into title (name, code,type) values ('DASA ON','DASA3','ACTION');
insert into title (name, code,type) values ('DESKTOP ON','DESK3','ACTION');
insert into title (name, code,type) values ('DEXCO ON','DXCO3','ACTION');
insert into title (name, code,type) values ('DEXXOS PAR ON','DEXP3','ACTION');
insert into title (name, code,type) values ('DIMED ON','PNVL3','ACTION');
insert into title (name, code,type) values ('DIRECIONAL ON','DIRR3','ACTION');
insert into title (name, code,type) values ('DOMMO ON','DMMO3','ACTION');
insert into title (name, code,type) values ('ECORODOVIAS ON','ECOR3','ACTION');
insert into title (name, code,type) values ('ELETROBRAS ON','ELET3','ACTION');
insert into title (name, code,type) values ('ELETROBRAS PNB','ELET6','ACTION');
insert into title (name, code,type) values ('ELETROMIDIA ON','ELMD3','ACTION');
insert into title (name, code,type) values ('EMBRAER ON','EMBR3','ACTION');
insert into title (name, code,type) values ('ENAUTA PART ON','ENAT3','ACTION');
insert into title (name, code,type) values ('ENERGIAS BR ON','ENBR3','ACTION');
insert into title (name, code,type) values ('ENERGISA UNT','ENGI11','ACTION');
insert into title (name, code,type) values ('ENEVA ON','ENEV3','ACTION');
insert into title (name, code,type) values ('ENGIE BRASIL ON','EGIE3','ACTION');
insert into title (name, code,type) values ('ENJOEI ON','ENJU3','ACTION');
insert into title (name, code,type) values ('EQUATORIAL ON','EQTL3','ACTION');
insert into title (name, code,type) values ('ESPACOLASER ON','ESPA3','ACTION');
insert into title (name, code,type) values ('ETERNIT ON','ETER3','ACTION');
insert into title (name, code,type) values ('ETF BRA IBOV CI','BOVB11','ACTION');
insert into title (name, code,type) values ('ETHER HASH CI','ETHE11','ACTION');
insert into title (name, code,type) values ('EVEN ON','EVEN3','ACTION');
insert into title (name, code,type) values ('EXXON MOBIL DRN','EXXO34','ACTION');
insert into title (name, code,type) values ('EZTEC ON','EZTC3','ACTION');
insert into title (name, code,type) values ('FER HERINGER ON','FHER3','ACTION');
insert into title (name, code,type) values ('FERBASA PN','FESA4','ACTION');
insert into title (name, code,type) values ('FIAGRO RIZA CI ER','RZAG11','ACTION');
insert into title (name, code,type) values ('FINAM CI *','FNAM11','ACTION');
insert into title (name, code,type) values ('FINOR CI *','FNOR11','ACTION');
insert into title (name, code,type) values ('FLEURY ON','FLRY3','ACTION');
insert into title (name, code,type) values ('FOCUS ON ON','POWE3','ACTION');
insert into title (name, code,type) values ('FRAS-LE ON','FRAS3','ACTION');
insert into title (name, code,type) values ('GAFISA ON','GFSA3','ACTION');
insert into title (name, code,type) values ('GENERAL MOT DRN','GMCO34','ACTION');
insert into title (name, code,type) values ('GERDAU ON ED','GGBR3','ACTION');
insert into title (name, code,type) values ('GERDAU PN ED','GGBR4','ACTION');
insert into title (name, code,type) values ('GERDAU MET ON ED','GOAU3','ACTION');
insert into title (name, code,type) values ('GERDAU MET PN ED','GOAU4','ACTION');
insert into title (name, code,type) values ('GETNET BR UNT','GETT11','ACTION');
insert into title (name, code,type) values ('GETNINJAS ON','NINJ3','ACTION');
insert into title (name, code,type) values ('GOL PN','GOLL4','ACTION');
insert into title (name, code,type) values ('GOLD TRUST DRN','BIAU39','ACTION');
insert into title (name, code,type) values ('GPS ON','GGPS3','ACTION');
insert into title (name, code,type) values ('GRENDENE ON','GRND3','ACTION');
insert into title (name, code,type) values ('GRUPO MATEUS ON','GMAT3','ACTION');
insert into title (name, code,type) values ('GRUPO NATURA ON','NTCO3','ACTION');
insert into title (name, code,type) values ('GRUPO SBF ON','SBFG3','ACTION');
insert into title (name, code,type) values ('GRUPO SOMA ON','SOMA3','ACTION');
insert into title (name, code,type) values ('GUARARAPES ON','GUAR3','ACTION');
insert into title (name, code,type) values ('HAPVIDA ON','HAPV3','ACTION');
insert into title (name, code,type) values ('HASHDEX NCI CI','HASH11','ACTION');
insert into title (name, code,type) values ('HELBOR ON','HBOR3','ACTION');
insert into title (name, code,type) values ('HIDROVIAS ON','HBSA3','ACTION');
insert into title (name, code,type) values ('HOME DEPOT DRN ED','HOME34','ACTION');
insert into title (name, code,type) values ('HYPERA ON','HYPE3','ACTION');
insert into title (name, code,type) values ('IGUATEMI S.A ON','IGTI3','ACTION');
insert into title (name, code,type) values ('IGUATEMI S.A UNT','IGTI11','ACTION');
insert into title (name, code,type) values ('IHPARDINI ON','PARD3','ACTION');
insert into title (name, code,type) values ('IMC S/A ON','MEAL3','ACTION');
insert into title (name, code,type) values ('INDS ROMI ON','ROMI3','ACTION');
insert into title (name, code,type) values ('INEPAR ON','INEP3','ACTION');
insert into title (name, code,type) values ('INFRACOMM ON','IFCM3','ACTION');
insert into title (name, code,type) values ('INTELBRAS ON ED','INTB3','ACTION');
insert into title (name, code,type) values ('INVESTO JOGO CI','JOGO11','ACTION');
insert into title (name, code,type) values ('IOCHP-MAXION ON','MYPK3','ACTION');
insert into title (name, code,type) values ('IRANI ON ED','RANI3','ACTION');
insert into title (name, code,type) values ('IRBBRASIL RE ON','IRBR3','ACTION');
insert into title (name, code,type) values ('ISHARE SP500 CI','IVVB11','ACTION');
insert into title (name, code,type) values ('ISHARES BOVA CI','BOVA11','ACTION');
insert into title (name, code,type) values ('ISHARES SMAL CI','SMAL11','ACTION');
insert into title (name, code,type) values ('IT NOW IBOV CI','BOVV11','ACTION');
insert into title (name, code,type) values ('IT NOW IDIV CI','DIVO11','ACTION');
insert into title (name, code,type) values ('IT NOW IFNC CI','FIND11','ACTION');
insert into title (name, code,type) values ('IT NOW IMA-B F11','IMAB11','ACTION');
insert into title (name, code,type) values ('IT NOW IMAT CI','MATB11','ACTION');
insert into title (name, code,type) values ('IT NOW PIBB CI','PIBB11','ACTION');
insert into title (name, code,type) values ('IT NOW SMALL CI','SMAC11','ACTION');
insert into title (name, code,type) values ('IT NOW SPXI CI','SPXI11','ACTION');
insert into title (name, code,type) values ('ITAUSA ON','ITSA3','ACTION');
insert into title (name, code,type) values ('ITAUSA PN','ITSA4','ACTION');
insert into title (name, code,type) values ('ITAUUNIBANCO ON EJ','ITUB3','ACTION');
insert into title (name, code,type) values ('ITAUUNIBANCO PN EJ','ITUB4','ACTION');
insert into title (name, code,type) values ('JALLESMACHAD ON','JALL3','ACTION');
insert into title (name, code,type) values ('JBS ON','JBSS3','ACTION');
insert into title (name, code,type) values ('JHSF PART ON ED','JHSF3','ACTION');
insert into title (name, code,type) values ('JOHNSON DRN','JNJB34','ACTION');
insert into title (name, code,type) values ('JPMORGAN DRN','JPMC34','ACTION');
insert into title (name, code,type) values ('JSL ON','JSLG3','ACTION');
insert into title (name, code,type) values ('KEPLER WEBER ON','KEPL3','ACTION');
insert into title (name, code,type) values ('KINEA INFRAF FIDCER','KDIF11','ACTION');
insert into title (name, code,type) values ('KLABIN S/A PN','KLBN4','ACTION');
insert into title (name, code,type) values ('KLABIN S/A UNT','KLBN11','ACTION');
insert into title (name, code,type) values ('LAVVI ON','LAVV3','ACTION');
insert into title (name, code,type) values ('LIGHT S/A ON','LIGT3','ACTION');
insert into title (name, code,type) values ('LOCALIZA ON','RENT3','ACTION');
insert into title (name, code,type) values ('LOCAMERICA ON','LCAM3','ACTION');
insert into title (name, code,type) values ('LOCAWEB ON','LWSA3','ACTION');
insert into title (name, code,type) values ('LOG COM PROP ON','LOGG3','ACTION');
insert into title (name, code,type) values ('LOG-IN ON','LOGN3','ACTION');
insert into title (name, code,type) values ('LOJAS MARISA ON','AMAR3','ACTION');
insert into title (name, code,type) values ('LOJAS RENNER ON','LREN3','ACTION');
insert into title (name, code,type) values ('LOPES BRASIL ON','LPSB3','ACTION');
insert into title (name, code,type) values ('LUPATECH ON','LUPA3','ACTION');
insert into title (name, code,type) values ('M.DIASBRANCO ON','MDIA3','ACTION');
insert into title (name, code,type) values ('MAGAZ LUIZA ON','MGLU3','ACTION');
insert into title (name, code,type) values ('MARCOPOLO PN','POMO4','ACTION');
insert into title (name, code,type) values ('MARFRIG ON','MRFG3','ACTION');
insert into title (name, code,type) values ('MASTERCARD DRN','MSCD34','ACTION');
insert into title (name, code,type) values ('MATER DEI ON','MATD3','ACTION');
insert into title (name, code,type) values ('MCDONALDS DRN','MCDC34','ACTION');
insert into title (name, code,type) values ('MELIUZ ON','CASH3','ACTION');
insert into title (name, code,type) values ('MELNICK ON','MELK3','ACTION');
insert into title (name, code,type) values ('MERCADOLIBRE DRN','MELI34','ACTION');
insert into title (name, code,type) values ('META PLAT DRN','FBOK34','ACTION');
insert into title (name, code,type) values ('METAL LEVE ON','LEVE3','ACTION');
insert into title (name, code,type) values ('MICRON TECHN DRN','MUTC34','ACTION');
insert into title (name, code,type) values ('MICROSOFT DRN','MSFT34','ACTION');
insert into title (name, code,type) values ('MILLS ON','MILS3','ACTION');
insert into title (name, code,type) values ('MINERVA ON','BEEF3','ACTION');
insert into title (name, code,type) values ('MITRE REALTY ON ED','MTRE3','ACTION');
insert into title (name, code,type) values ('MOBLY ON','MBLY3','ACTION');
insert into title (name, code,type) values ('MODALMAIS UNT','MODL11','ACTION');
insert into title (name, code,type) values ('MODERNA INC DRN','M1RN34','ACTION');
insert into title (name, code,type) values ('MOSAICO ON','MOSI3','ACTION');
insert into title (name, code,type) values ('MOURA DUBEUX ON','MDNE3','ACTION');
insert into title (name, code,type) values ('MOVIDA ON','MOVI3','ACTION');
insert into title (name, code,type) values ('MRV ON','MRVE3','ACTION');
insert into title (name, code,type) values ('MSCI ACWI DRN','BACW39','ACTION');
insert into title (name, code,type) values ('MULTILASER ON','MLAS3','ACTION');
insert into title (name, code,type) values ('MULTIPLAN ON','MULT3','ACTION');
insert into title (name, code,type) values ('NEOENERGIA ON','NEOE3','ACTION');
insert into title (name, code,type) values ('NEOGRID ON','NGRD3','ACTION');
insert into title (name, code,type) values ('NETFLIX DRN','NFLX34','ACTION');
insert into title (name, code,type) values ('NIKE DRN ED','NIKE34','ACTION');
insert into title (name, code,type) values ('NU-NUBANK DR3','NUBR33','ACTION');
insert into title (name, code,type) values ('NVIDIA CORP DRN ED','NVDC34','ACTION');
insert into title (name, code,type) values ('OCCIDENT PTR DRN ED','OXYP34','ACTION');
insert into title (name, code,type) values ('OCEANPACT ON','OPCT3','ACTION');
insert into title (name, code,type) values ('ODONTOPREV ON','ODPV3','ACTION');
insert into title (name, code,type) values ('OI ON ES','OIBR3','ACTION');
insert into title (name, code,type) values ('OI PN ES','OIBR4','ACTION');
insert into title (name, code,type) values ('OMEGAENERGIA ON','MEGA3','ACTION');
insert into title (name, code,type) values ('ONCOCLINICAS ON','ONCO3','ACTION');
insert into title (name, code,type) values ('ORIZON ON','ORVR3','ACTION');
insert into title (name, code,type) values ('P.ACUCAR-CBD ON','PCAR3','ACTION');
insert into title (name, code,type) values ('PAGUE MENOS ON','PGMN3','ACTION');
insert into title (name, code,type) values ('PARANAPANEMA ON','PMAM3','ACTION');
insert into title (name, code,type) values ('PAYPAL HOLD DRN','PYPL34','ACTION');
insert into title (name, code,type) values ('PETROBRAS ON','PETR3','ACTION');
insert into title (name, code,type) values ('PETROBRAS PN','PETR4','ACTION');
insert into title (name, code,type) values ('PETRORECSA ON','RECV3','ACTION');
insert into title (name, code,type) values ('PETRORIO ON','PRIO3','ACTION');
insert into title (name, code,type) values ('PETZ ON','PETZ3','ACTION');
insert into title (name, code,type) values ('PFIZER DRN','PFIZ34','ACTION');
insert into title (name, code,type) values ('PG DRN','PGCO34','ACTION');
insert into title (name, code,type) values ('PLANOEPLANO ON','PLPL3','ACTION');
insert into title (name, code,type) values ('PORTO SEGURO ON','PSSA3','ACTION');
insert into title (name, code,type) values ('PORTOBELLO ON','PTBL3','ACTION');
insert into title (name, code,type) values ('POSITIVO TEC ON','POSI3','ACTION');
insert into title (name, code,type) values ('QR BITCOIN CI','QBTC11','ACTION');
insert into title (name, code,type) values ('QR ETHER CI','QETH11','ACTION');
insert into title (name, code,type) values ('QUALICORP ON','QUAL3','ACTION');
insert into title (name, code,type) values ('QUERO-QUERO ON','LJQQ3','ACTION');
insert into title (name, code,type) values ('RAIADROGASIL ON','RADL3','ACTION');
insert into title (name, code,type) values ('RAIZEN PN','RAIZ4','ACTION');
insert into title (name, code,type) values ('RANDON PART PN','RAPT4','ACTION');
insert into title (name, code,type) values ('RECRUSUL ON','RCSL3','ACTION');
insert into title (name, code,type) values ('REDE D OR ON','RDOR3','ACTION');
insert into title (name, code,type) values ('RUMO S.A. ON','RAIL3','ACTION');
insert into title (name, code,type) values ('SABESP ON','SBSP3','ACTION');
insert into title (name, code,type) values ('SALESFORCE DRN','SSFO34','ACTION');
insert into title (name, code,type) values ('SANEPAR ON','SAPR3','ACTION');
insert into title (name, code,type) values ('SANEPAR PN','SAPR4','ACTION');
insert into title (name, code,type) values ('SANEPAR UNT','SAPR11','ACTION');
insert into title (name, code,type) values ('SANTANDER BR ON','SANB3','ACTION');
insert into title (name, code,type) values ('SANTANDER BR PN','SANB4','ACTION');
insert into title (name, code,type) values ('SANTANDER BR UNT','SANB11','ACTION');
insert into title (name, code,type) values ('SANTOS BRP ON','STBP3','ACTION');
insert into title (name, code,type) values ('SAO MARTINHO ON','SMTO3','ACTION');
insert into title (name, code,type) values ('SCHULZ PN','SHUL4','ACTION');
insert into title (name, code,type) values ('SEQUOIA LOG ON','SEQL3','ACTION');
insert into title (name, code,type) values ('SER EDUCA ON','SEER3','ACTION');
insert into title (name, code,type) values ('SID NACIONAL ON','CSNA3','ACTION');
insert into title (name, code,type) values ('SIMPAR ON','SIMH3','ACTION');
insert into title (name, code,type) values ('SINQIA ON','SQIA3','ACTION');
insert into title (name, code,type) values ('SLC AGRICOLA ON','SLCE3','ACTION');
insert into title (name, code,type) values ('SMART FIT ON','SMFT3','ACTION');
insert into title (name, code,type) values ('SP500 VALUE DRN','BIVE39','ACTION');
insert into title (name, code,type) values ('SUL AMERICA UNT','SULA11','ACTION');
insert into title (name, code,type) values ('SUZANO S.A. ON','SUZB3','ACTION');
insert into title (name, code,type) values ('SYN PROP TEC ON','SYNE3','ACTION');
insert into title (name, code,type) values ('TAESA ON','TAEE3','ACTION');
insert into title (name, code,type) values ('TAESA PN','TAEE4','ACTION');
insert into title (name, code,type) values ('TAESA UNT','TAEE11','ACTION');
insert into title (name, code,type) values ('TAIWANSMFAC DRN','TSMC34','ACTION');
insert into title (name, code,type) values ('TAURUS ARMAS PN','TASA4','ACTION');
insert into title (name, code,type) values ('TC ON','TRAD3','ACTION');
insert into title (name, code,type) values ('TECHNOS ON','TECN3','ACTION');
insert into title (name, code,type) values ('TECNISA ON','TCSA3','ACTION');
insert into title (name, code,type) values ('TEGMA ON','TGMA3','ACTION');
insert into title (name, code,type) values ('TELEF BRASIL ON EJ','VIVT3','ACTION');
insert into title (name, code,type) values ('TENDA ON','TEND3','ACTION');
insert into title (name, code,type) values ('TESLA INC DRN','TSLA34','ACTION');
insert into title (name, code,type) values ('TIM ON','TIMS3','ACTION');
insert into title (name, code,type) values ('TIME FOR FUN ON','SHOW3','ACTION');
insert into title (name, code,type) values ('TOTVS ON','TOTS3','ACTION');
insert into title (name, code,type) values ('TRAN PAULIST PN','TRPL4','ACTION');
insert into title (name, code,type) values ('TREND ACWI CI','ACWI11','ACTION');
insert into title (name, code,type) values ('TREND CHINA CI','XINA11','ACTION');
insert into title (name, code,type) values ('TREND ESG D CI','ESGD11','ACTION');
insert into title (name, code,type) values ('TREND ESG US CI','ESGU11','ACTION');
insert into title (name, code,type) values ('TREND EUROPA CI','EURP11','ACTION');
insert into title (name, code,type) values ('TREND IBOVX CI','BOVX11','ACTION');
insert into title (name, code,type) values ('TREND NASDAQ CI','NASD11','ACTION');
insert into title (name, code,type) values ('TREND OURO CI','GOLD11','ACTION');
insert into title (name, code,type) values ('TREND US LRG CI','USAL11','ACTION');
insert into title (name, code,type) values ('TRISUL ON','TRIS3','ACTION');
insert into title (name, code,type) values ('TRUSTMSCI US DRN','BEGU39','ACTION');
insert into title (name, code,type) values ('TUPY ON','TUPY3','ACTION');
insert into title (name, code,type) values ('UBER TECH IN DRN','U1BE34','ACTION');
insert into title (name, code,type) values ('ULTRAPAR ON ED','UGPA3','ACTION');
insert into title (name, code,type) values ('UNIFIQUE ON','FIQE3','ACTION');
insert into title (name, code,type) values ('UNIPAR ON','UNIP3','ACTION');
insert into title (name, code,type) values ('UNIPAR PNB','UNIP6','ACTION');
insert into title (name, code,type) values ('UNITEDHEALTH DRN ED','UNHH34','ACTION');
insert into title (name, code,type) values ('USIMINAS ON','USIM3','ACTION');
insert into title (name, code,type) values ('USIMINAS PNA','USIM5','ACTION');
insert into title (name, code,type) values ('VALE ON ED','VALE3','ACTION');
insert into title (name, code,type) values ('VALID ON','VLID3','ACTION');
insert into title (name, code,type) values ('VAMOS ON','VAMO3','ACTION');
insert into title (name, code,type) values ('VIA ON','VIIA3','ACTION');
insert into title (name, code,type) values ('VIBRA ON','VBBR3','ACTION');
insert into title (name, code,type) values ('VISA INC DRN','VISA34','ACTION');
insert into title (name, code,type) values ('VITTIA ON','VITT3','ACTION');
insert into title (name, code,type) values ('VIVARA S.A. ON','VIVA3','ACTION');
insert into title (name, code,type) values ('VIVEO ON','VVEO3','ACTION');
insert into title (name, code,type) values ('VIVER ON','VIVR3','ACTION');
insert into title (name, code,type) values ('VULCABRAS ON','VULC3','ACTION');
insert into title (name, code,type) values ('WALT DISNEY DRN','DISB34','ACTION');
insert into title (name, code,type) values ('WDC NETWORKS ON','LVTC3','ACTION');
insert into title (name, code,type) values ('WEG ON','WEGE3','ACTION');
insert into title (name, code,type) values ('WELLS FARGO DRN','WFCO34','ACTION');
insert into title (name, code,type) values ('WESTWING ON','WEST3','ACTION');
insert into title (name, code,type) values ('WILSON SONS ON','PORT3','ACTION');
insert into title (name, code,type) values ('WIZ S.A. ON','WIZS3','ACTION');
insert into title (name, code,type) values ('XP INC DR1','XPBR31','ACTION');
insert into title (name, code,type) values ('YDUQS PART ON','YDUQ3','ACTION');
insert into title (name, code,type) values ('YDUQS PART ON','YDUQ3','FII');
insert into title (name, code,type) values ('FII INTER IT','FII INTER IT11','FII');
insert into title (name, code,type) values ('FII LAVOURA','FII LAVOURA11','FII');
insert into title (name, code,type) values ('FII AFHI CRI','FII AFHI CRI11','FII');
insert into title (name, code,type) values ('FII ALIANZFF','FII ALIANZFF11','FII');
insert into title (name, code,type) values ('FII MULT OF1','FII MULT OF111','FII');
insert into title (name, code,type) values ('FII ALIANZA','FII ALIANZA11','FII');
insert into title (name, code,type) values ('FII AUTONOMY','FII AUTONOMY11','FII');
insert into title (name, code,type) values ('FII BEES CRI','FII BEES CRI11','FII');
insert into title (name, code,type) values ('FII BANRISUL','FII BANRISUL11','FII');
insert into title (name, code,type) values ('FII BARZEL','FII BARZEL11','FII');
insert into title (name, code,type) values ('FII BASILICA','FII BASILICA11','FII');
insert into title (name, code,type) values ('FII BB PROGR','FII BB PROGR11','FII');
insert into title (name, code,type) values ('FII BB FOF','FII BB FOF11','FII');
insert into title (name, code,type) values ('FII BB PRGII','FII BB PRGII11','FII');
insert into title (name, code,type) values ('FII BB RECIM','FII BB RECIM11','FII');
insert into title (name, code,type) values ('FII BB CORP','FII BB CORP11','FII');
insert into title (name, code,type) values ('FII BB PAPII','FII BB PAPII11','FII');
insert into title (name, code,type) values ('FII BB R PAP','FII BB R PAP11','FII');
insert into title (name, code,type) values ('FII BLUECAP','FII BLUECAP11','FII');
insert into title (name, code,type) values ('FII BLUE AAA','FII BLUE AAA11','FII');
insert into title (name, code,type) values ('FII BLUE CRI','FII BLUE CRI11','FII');
insert into title (name, code,type) values ('FII BLUE LOG','FII BLUE LOG11','FII');
insert into title (name, code,type) values ('FII BLUEMAC','FII BLUEMAC11','FII');
insert into title (name, code,type) values ('FII BLUE FOF','FII BLUE FOF11','FII');
insert into title (name, code,type) values ('FII BR PROPE','FII BR PROPE11','FII');
insert into title (name, code,type) values ('FII BCIA','FII BCIA11','FII');
insert into title (name, code,type) values ('FII BRE VIC','FII BRE VIC11','FII');
insert into title (name, code,type) values ('FII BRREALTY','FII BRREALTY11','FII');
insert into title (name, code,type) values ('FII DEA CARE','FII DEA CARE11','FII');
insert into title (name, code,type) values ('FII BRESCO','FII BRESCO11','FII');
insert into title (name, code,type) values ('FII BRIO CRE','FII BRIO CRE11','FII');
insert into title (name, code,type) values ('FII BRIO ME','FII BRIO ME11','FII');
insert into title (name, code,type) values ('FII BRIO II','FII BRIO II11','FII');
insert into title (name, code,type) values ('FII BRIO III','FII BRIO III11','FII');
insert into title (name, code,type) values ('FII BRIO IV','FII BRIO IV11','FII');
insert into title (name, code,type) values ('FII BS2','FII BS211','FII');
insert into title (name, code,type) values ('FII BTLG','FII BTLG11','FII');
insert into title (name, code,type) values ('FII BTOWERS','FII BTOWERS11','FII');
insert into title (name, code,type) values ('FII BTSP I','FII BTSP I11','FII');
insert into title (name, code,type) values ('FII BTSP II','FII BTSP II11','FII');
insert into title (name, code,type) values ('FII CX RBRA2','FII CX RBRA211','FII');
insert into title (name, code,type) values ('FII CX RBRAV','FII CX RBRAV11','FII');
insert into title (name, code,type) values ('FII CANVAS','FII CANVAS11','FII');
insert into title (name, code,type) values ('FII CAP REIT','FII CAP REIT11','FII');
insert into title (name, code,type) values ('FII CAPI SEC','FII CAPI SEC11','FII');
insert into title (name, code,type) values ('CARTESIA FII','CARTESIA FII11','FII');
insert into title (name, code,type) values ('FII C BRANCO','FII C BRANCO11','FII');
insert into title (name, code,type) values ('FII CF2','FII CF211','FII');
insert into title (name, code,type) values ('FII CJCTOWER','FII CJCTOWER11','FII');
insert into title (name, code,type) values ('FII CORE MET','FII CORE MET11','FII');
insert into title (name, code,type) values ('FII CSHG FOF','FII CSHG FOF11','FII');
insert into title (name, code,type) values ('FII CSHG LOG','FII CSHG LOG11','FII');
insert into title (name, code,type) values ('FII CSHGPRIM','FII CSHGPRIM11','FII');
insert into title (name, code,type) values ('FII HG REAL','FII HG REAL11','FII');
insert into title (name, code,type) values ('FII CSHG CRI','FII CSHG CRI11','FII');
insert into title (name, code,type) values ('FII CSHG URB','FII CSHG URB11','FII');
insert into title (name, code,type) values ('FII CSHG RSD','FII CSHG RSD11','FII');
insert into title (name, code,type) values ('FII CVPAR','FII CVPAR11','FII');
insert into title (name, code,type) values ('FII CYRELA','FII CYRELA11','FII');
insert into title (name, code,type) values ('FII DEL MONT','FII DEL MONT11','FII');
insert into title (name, code,type) values ('FII DEVANT','FII DEVANT11','FII');
insert into title (name, code,type) values ('FII DIAMANTE','FII DIAMANTE11','FII');
insert into title (name, code,type) values ('FII DOVEL','FII DOVEL11','FII');
insert into title (name, code,type) values ('FII ENERGY','FII ENERGY11','FII');
insert into title (name, code,type) values ('FII EQI RECE','FII EQI RECE11','FII');
insert into title (name, code,type) values ('FII ESTOQ RJ','FII ESTOQ RJ11','FII');
insert into title (name, code,type) values ('FII EUROPA','FII EUROPA11','FII');
insert into title (name, code,type) values ('FII EVEN II','FII EVEN II11','FII');
insert into title (name, code,type) values ('FII EV KINEA','FII EV KINEA11','FII');
insert into title (name, code,type) values ('FII EXES','FII EXES11','FII');
insert into title (name, code,type) values ('FII FL RECEB','FII FL RECEB11','FII');
insert into title (name, code,type) values ('FII FATOR VE','FII FATOR VE11','FII');
insert into title (name, code,type) values ('FII BRASILIO','FII BRASILIO11','FII');
insert into title (name, code,type) values ('FII LEBLON','FII LEBLON11','FII');
insert into title (name, code,type) values ('FII MAUA HY','FII MAUA HY11','FII');
insert into title (name, code,type) values ('FII MAUA MPD','FII MAUA MPD11','FII');
insert into title (name, code,type) values ('FII BREI','FII BREI11','FII');
insert into title (name, code,type) values ('FII GUARD MU','FII GUARD MU11','FII');
insert into title (name, code,type) values ('FII BTG CRI','FII BTG CRI11','FII');
insert into title (name, code,type) values ('FII MTRS','FII MTRS11','FII');
insert into title (name, code,type) values ('FII ANCAR IC','FII ANCAR IC11','FII');
insert into title (name, code,type) values ('FII ANH EDUC','FII ANH EDUC11','FII');
insert into title (name, code,type) values ('FII BMBRC LC','FII BMBRC LC11','FII');
insert into title (name, code,type) values ('FII BRLPROP','FII BRLPROP11','FII');
insert into title (name, code,type) values ('FII BC FUND','FII BC FUND11','FII');
insert into title (name, code,type) values ('FII EXCELLEN','FII EXCELLEN11','FII');
insert into title (name, code,type) values ('FII BC FFII','FII BC FFII11','FII');
insert into title (name, code,type) values ('FII CAMPUSFL','FII CAMPUSFL11','FII');
insert into title (name, code,type) values ('FII CENESP','FII CENESP11','FII');
insert into title (name, code,type) values ('FII CEO CCP','FII CEO CCP11','FII');
insert into title (name, code,type) values ('FII ALMIRANT','FII ALMIRANT11','FII');
insert into title (name, code,type) values ('FII GALERIA','FII GALERIA11','FII');
insert into title (name, code,type) values ('FII ELDORADO','FII ELDORADO11','FII');
insert into title (name, code,type) values ('FII FLORIPA','FII FLORIPA11','FII');
insert into title (name, code,type) values ('FII CRIANCA','FII CRIANCA11','FII');
insert into title (name, code,type) values ('FII LOURDES','FII LOURDES11','FII');
insert into title (name, code,type) values ('FII HOTEL MX','FII HOTEL MX11','FII');
insert into title (name, code,type) values ('FII MAX RET','FII MAX RET11','FII');
insert into title (name, code,type) values ('FII NOVOHORI','FII NOVOHORI11','FII');
insert into title (name, code,type) values ('FII D PEDRO','FII D PEDRO11','FII');
insert into title (name, code,type) values ('FII PTO BAND','FII PTO BAND11','FII');
insert into title (name, code,type) values ('FII RBR DES','FII RBR DES11','FII');
insert into title (name, code,type) values ('FII RBRHGRAD','FII RBRHGRAD11','FII');
insert into title (name, code,type) values ('FII REC RECE','FII REC RECE11','FII');
insert into title (name, code,type) values ('FII REC REND','FII REC REND11','FII');
insert into title (name, code,type) values ('FII SHOPJSUL','FII SHOPJSUL11','FII');
insert into title (name, code,type) values ('FII SHOP PDP','FII SHOP PDP11','FII');
insert into title (name, code,type) values ('FII SIA CORP','FII SIA CORP11','FII');
insert into title (name, code,type) values ('FII TBOFFICE','FII TBOFFICE11','FII');
insert into title (name, code,type) values ('FII TORRE AL','FII TORRE AL11','FII');
insert into title (name, code,type) values ('FII TORRE NO','FII TORRE NO11','FII');
insert into title (name, code,type) values ('FII OLIMPIA','FII OLIMPIA11','FII');
insert into title (name, code,type) values ('FII NCH EQI','FII NCH EQI11','FII');
insert into title (name, code,type) values ('FII OURI FOF','FII OURI FOF11','FII');
insert into title (name, code,type) values ('FII WTC SP','FII WTC SP11','FII');
insert into title (name, code,type) values ('FII V2 PROP','FII V2 PROP11','FII');
insert into title (name, code,type) values ('FII VBI LOG','FII VBI LOG11','FII');
insert into title (name, code,type) values ('FII BARIGUI','FII BARIGUI11','FII');
insert into title (name, code,type) values ('FII BRHOTEIS','FII BRHOTEIS11','FII');
insert into title (name, code,type) values ('FII ABSOLUTO','FII ABSOLUTO11','FII');
insert into title (name, code,type) values ('FII B VAREJO','FII B VAREJO11','FII');
insert into title (name, code,type) values ('FII BTG SHOP','FII BTG SHOP11','FII');
insert into title (name, code,type) values ('FII BTG TAGR','FII BTG TAGR11','FII');
insert into title (name, code,type) values ('FII CAIXA CI','FII CAIXA CI11','FII');
insert into title (name, code,type) values ('FII CX CEDAE','FII CX CEDAE11','FII');
insert into title (name, code,type) values ('FII CX TRX','FII CX TRX11','FII');
insert into title (name, code,type) values ('FII C TEXTIL','FII C TEXTIL11','FII');
insert into title (name, code,type) values ('FII CJ','FII CJ11','FII');
insert into title (name, code,type) values ('FII S F LIMA','FII S F LIMA11','FII');
insert into title (name, code,type) values ('FII OURINVES','FII OURINVES11','FII');
insert into title (name, code,type) values ('FII EUROPAR','FII EUROPAR11','FII');
insert into title (name, code,type) values ('FII GEN SEV','FII GEN SEV11','FII');
insert into title (name, code,type) values ('FII ABC IMOB','FII ABC IMOB11','FII');
insert into title (name, code,type) values ('FII G TOWERS','FII G TOWERS11','FII');
insert into title (name, code,type) values ('FII HABITAT','FII HABITAT11','FII');
insert into title (name, code,type) values ('FII UNIMED C','FII UNIMED C11','FII');
insert into title (name, code,type) values ('FII H UNIMED','FII H UNIMED11','FII');
insert into title (name, code,type) values ('FII INDL BR','FII INDL BR11','FII');
insert into title (name, code,type) values ('FII INFRA RE','FII INFRA RE11','FII');
insert into title (name, code,type) values ('FII MEMORIAL','FII MEMORIAL11','FII');
insert into title (name, code,type) values ('FII MERC BR','FII MERC BR11','FII');
insert into title (name, code,type) values ('FII MOGNO','FII MOGNO11','FII');
insert into title (name, code,type) values ('FII MV9','FII MV911','FII');
insert into title (name, code,type) values ('FII NESTPAR','FII NESTPAR11','FII');
insert into title (name, code,type) values ('FII OURILOG','FII OURILOG11','FII');
insert into title (name, code,type) values ('FII PANAMBY','FII PANAMBY11','FII');
insert into title (name, code,type) values ('FII P NEGRA','FII P NEGRA11','FII');
insert into title (name, code,type) values ('FII POLO II','FII POLO II11','FII');
insert into title (name, code,type) values ('FII POLO SHO','FII POLO SHO11','FII');
insert into title (name, code,type) values ('FII A BRANCA','FII A BRANCA11','FII');
insert into title (name, code,type) values ('FII RBR PCRI','FII RBR PCRI11','FII');
insert into title (name, code,type) values ('FII RBR PROP','FII RBR PROP11','FII');
insert into title (name, code,type) values ('FII RIOB RC','FII RIOB RC11','FII');
insert into title (name, code,type) values ('FII RIOB ED','FII RIOB ED11','FII');
insert into title (name, code,type) values ('FII RIOB VA','FII RIOB VA11','FII');
insert into title (name, code,type) values ('FII RIONEGRO','FII RIONEGRO11','FII');
insert into title (name, code,type) values ('FII SAO FER','FII SAO FER11','FII');
insert into title (name, code,type) values ('FII SC 401','FII SC 40111','FII');
insert into title (name, code,type) values ('FII SCP','FII SCP11','FII');
insert into title (name, code,type) values ('FII SDI LOG','FII SDI LOG11','FII');
insert into title (name, code,type) values ('FII HIGIENOP','FII HIGIENOP11','FII');
insert into title (name, code,type) values ('FII TG ATIVO','FII TG ATIVO11','FII');
insert into title (name, code,type) values ('FII THE ONE','FII THE ONE11','FII');
insert into title (name, code,type) values ('FII VEREDA','FII VEREDA11','FII');
insert into title (name, code,type) values ('FII V PARQUE','FII V PARQUE11','FII');
insert into title (name, code,type) values ('FII VIDANOVA','FII VIDANOVA11','FII');
insert into title (name, code,type) values ('FII VOT LOG','FII VOT LOG11','FII');
insert into title (name, code,type) values ('FII VOT SEC','FII VOT SEC11','FII');
insert into title (name, code,type) values ('FII VOT SHOP','FII VOT SHOP11','FII');
insert into title (name, code,type) values ('FII UNIDADES','FII UNIDADES11','FII');
insert into title (name, code,type) values ('FII FOF BREI','FII FOF BREI11','FII');
insert into title (name, code,type) values ('FII MOGNO ID','FII MOGNO ID11','FII');
insert into title (name, code,type) values ('FII PLURAL R','FII PLURAL R11','FII');
insert into title (name, code,type) values ('FII PLUS','FII PLUS11','FII');
insert into title (name, code,type) values ('FII REC LOG','FII REC LOG11','FII');
insert into title (name, code,type) values ('FII VBI CRI','FII VBI CRI11','FII');
insert into title (name, code,type) values ('FII MAUA','FII MAUA11','FII');
insert into title (name, code,type) values ('FII GRPLMALL','FII GRPLMALL11','FII');
insert into title (name, code,type) values ('FII A TOWN','FII A TOWN11','FII');
insert into title (name, code,type) values ('FII ATRIO','FII ATRIO11','FII');
insert into title (name, code,type) values ('FII BTG AGRO','FII BTG AGRO11','FII');
insert into title (name, code,type) values ('FII CEF CORP','FII CEF CORP11','FII');
insert into title (name, code,type) values ('FII HOUSI','FII HOUSI11','FII');
insert into title (name, code,type) values ('FII MOGNO HT','FII MOGNO HT11','FII');
insert into title (name, code,type) values ('FII REC FOF','FII REC FOF11','FII');
insert into title (name, code,type) values ('FII VBI PRI','FII VBI PRI11','FII');
insert into title (name, code,type) values ('FII DEVA FOF','FII DEVA FOF11','FII');
insert into title (name, code,type) values ('FII MOGNO HG','FII MOGNO HG11','FII');
insert into title (name, code,type) values ('FII RB CFOF','FII RB CFOF11','FII');
insert into title (name, code,type) values ('FII VOTP V','FII VOTP V11','FII');
insert into title (name, code,type) values ('FII VOTP XII','FII VOTP XII11','FII');
insert into title (name, code,type) values ('FII MULT REN','FII MULT REN11','FII');
insert into title (name, code,type) values ('FII FED HY','FII FED HY11','FII');
insert into title (name, code,type) values ('FII IRIDIUM','FII IRIDIUM11','FII');
insert into title (name, code,type) values ('FII SBCLOG','FII SBCLOG11','FII');
insert into title (name, code,type) values ('FII S VAREJO','FII S VAREJO11','FII');
insert into title (name, code,type) values ('FII KINEAFOF','FII KINEAFOF11','FII');
insert into title (name, code,type) values ('FII OU RENDA','FII OU RENDA11','FII');
insert into title (name, code,type) values ('FII BLUE REC','FII BLUE REC11','FII');
insert into title (name, code,type) values ('FII DEV ONE','FII DEV ONE11','FII');
insert into title (name, code,type) values ('FII RBR III','FII RBR III11','FII');
insert into title (name, code,type) values ('FII ATHENA I','FII ATHENA I11','FII');
insert into title (name, code,type) values ('FII BRLPROII','FII BRLPROII11','FII');
insert into title (name, code,type) values ('FII CAIXA AG','FII CAIXA AG11','FII');
insert into title (name, code,type) values ('FII HBC REN','FII HBC REN11','FII');
insert into title (name, code,type) values ('FII MINT EDU','FII MINT EDU11','FII');
insert into title (name, code,type) values ('FII RIZA TX','FII RIZA TX11','FII');
insert into title (name, code,type) values ('FII ROOFTOPI','FII ROOFTOPI11','FII');
insert into title (name, code,type) values ('FII TOUR V','FII TOUR V11','FII');
insert into title (name, code,type) values ('FII GALAPAGO','FII GALAPAGO11','FII');
insert into title (name, code,type) values ('FII GLPG CRI','FII GLPG CRI11','FII');
insert into title (name, code,type) values ('FII GAZIT','FII GAZIT11','FII');
insert into title (name, code,type) values ('FII GENERAL','FII GENERAL11','FII');
insert into title (name, code,type) values ('','11','FII');
insert into title (name, code,type) values ('FII GGRCOVEP','FII GGRCOVEP11','FII');
insert into title (name, code,type) values ('FII GLP LOG','FII GLP LOG11','FII');
insert into title (name, code,type) values ('FII GP RCFA','FII GP RCFA11','FII');
insert into title (name, code,type) values ('FII GTIS LG','FII GTIS LG11','FII');
insert into title (name, code,type) values ('FII GUARDIAN','FII GUARDIAN11','FII');
insert into title (name, code,type) values ('FII HABIT II','FII HABIT II11','FII');
insert into title (name, code,type) values ('FII HAZ','FII HAZ11','FII');
insert into title (name, code,type) values ('FII HECTARE','FII HECTARE11','FII');
insert into title (name, code,type) values ('FII HECT DES','FII HECT DES11','FII');
insert into title (name, code,type) values ('FII HECT PRP','FII HECT PRP11','FII');
insert into title (name, code,type) values ('FII HECT CRI','FII HECT CRI11','FII');
insert into title (name, code,type) values ('FII HEDGEAAA','FII HEDGEAAA11','FII');
insert into title (name, code,type) values ('FII HATRIUM','FII HATRIUM11','FII');
insert into title (name, code,type) values ('FII HEDGEBS','FII HEDGEBS11','FII');
insert into title (name, code,type) values ('FII HEDGELOG','FII HEDGELOG11','FII');
insert into title (name, code,type) values ('FII HEDGE OF','FII HEDGE OF11','FII');
insert into title (name, code,type) values ('FII HREALTY','FII HREALTY11','FII');
insert into title (name, code,type) values ('FII HEDGEREC','FII HEDGEREC11','FII');
insert into title (name, code,type) values ('FII HEDGE SD','FII HEDGE SD11','FII');
insert into title (name, code,type) values ('FII HEDGEPDP','FII HEDGEPDP11','FII');
insert into title (name, code,type) values ('FII HTOPFOF3','FII HTOPFOF311','FII');
insert into title (name, code,type) values ('FII HGI CRI','FII HGI CRI11','FII');
insert into title (name, code,type) values ('FII HSI CRI','FII HSI CRI11','FII');
insert into title (name, code,type) values ('FII HSI LOG','FII HSI LOG11','FII');
insert into title (name, code,type) values ('FII HSI MALL','FII HSI MALL11','FII');
insert into title (name, code,type) values ('FII HSIRENDA','FII HSIRENDA11','FII');
insert into title (name, code,type) values ('FII HUSI','FII HUSI11','FII');
insert into title (name, code,type) values ('FII INTER IP','FII INTER IP11','FII');
insert into title (name, code,type) values ('FII INTER','FII INTER11','FII');
insert into title (name, code,type) values ('FII IRIM','FII IRIM11','FII');
insert into title (name, code,type) values ('FII JCDA I','FII JCDA I11','FII');
insert into title (name, code,type) values ('FII JBFO FOF','FII JBFO FOF11','FII');
insert into title (name, code,type) values ('FII JFDCAM','FII JFDCAM11','FII');
insert into title (name, code,type) values ('FII JFL LIV','FII JFL LIV11','FII');
insert into title (name, code,type) values ('FII JPPMOGNO','FII JPPMOGNO11','FII');
insert into title (name, code,type) values ('FII JPP CAPI','FII JPP CAPI11','FII');
insert into title (name, code,type) values ('FII JS A FIN','FII JS A FIN11','FII');
insert into title (name, code,type) values ('FII JS REAL','FII JS REAL11','FII');
insert into title (name, code,type) values ('FII JT PREV','FII JT PREV11','FII');
insert into title (name, code,type) values ('FII KILIMA','FII KILIMA11','FII');
insert into title (name, code,type) values ('FII KIVO','FII KIVO11','FII');
insert into title (name, code,type) values ('FII KINEA CR','FII KINEA CR11','FII');
insert into title (name, code,type) values ('FII KINEA HY','FII KINEA HY11','FII');
insert into title (name, code,type) values ('FII KII REAL','FII KII REAL11','FII');
insert into title (name, code,type) values ('FII KINEA IP','FII KINEA IP11','FII');
insert into title (name, code,type) values ('FII KINEA','FII KINEA11','FII');
insert into title (name, code,type) values ('FII KINEA RI','FII KINEA RI11','FII');
insert into title (name, code,type) values ('FII KINEA SC','FII KINEA SC11','FII');
insert into title (name, code,type) values ('FII LAGO PDR','FII LAGO PDR11','FII');
insert into title (name, code,type) values ('FII LATERES','FII LATERES11','FII');
insert into title (name, code,type) values ('FII LEGATUS','FII LEGATUS11','FII');
insert into title (name, code,type) values ('FII LESTE PA','FII LESTE PA11','FII');
insert into title (name, code,type) values ('FII LOFT I','FII LOFT I11','FII');
insert into title (name, code,type) values ('FII LOFT II','FII LOFT II11','FII');
insert into title (name, code,type) values ('FII LGCP INT','FII LGCP INT11','FII');
insert into title (name, code,type) values ('FII LUGGO','FII LUGGO11','FII');
insert into title (name, code,type) values ('FII MALLS BP','FII MALLS BP11','FII');
insert into title (name, code,type) values ('FII MMVE OP','FII MMVE OP11','FII');
insert into title (name, code,type) values ('FII MAUA DES','FII MAUA DES11','FII');
insert into title (name, code,type) values ('FII MAUA HF','FII MAUA HF11','FII');
insert into title (name, code,type) values ('FII MAXI REN','FII MAXI REN11','FII');
insert into title (name, code,type) values ('FII MERITO I','FII MERITO I11','FII');
insert into title (name, code,type) values ('FII MERITOFA','FII MERITOFA11','FII');
insert into title (name, code,type) values ('FII MOGNO LG','FII MOGNO LG11','FII');
insert into title (name, code,type) values ('FII MOGNO PR','FII MOGNO PR11','FII');
insert into title (name, code,type) values ('FII MORE ATV','FII MORE ATV11','FII');
insert into title (name, code,type) values ('FII MORE RE','FII MORE RE11','FII');
insert into title (name, code,type) values ('FII MORE CRI','FII MORE CRI11','FII');
insert into title (name, code,type) values ('FII MULTPROP','FII MULTPROP11','FII');
insert into title (name, code,type) values ('FII MULTSHOP','FII MULTSHOP11','FII');
insert into title (name, code,type) values ('FII MTGESTAO','FII MTGESTAO11','FII');
insert into title (name, code,type) values ('FII MULT OF2','FII MULT OF211','FII');
insert into title (name, code,type) values ('FII NAVI TOT','FII NAVI TOT11','FII');
insert into title (name, code,type) values ('FII NAVI RSD','FII NAVI RSD11','FII');
insert into title (name, code,type) values ('FII NEWPORT','FII NEWPORT11','FII');
insert into title (name, code,type) values ('FII NEWRU','FII NEWRU11','FII');
insert into title (name, code,type) values ('FII NOVA I','FII NOVA I11','FII');
insert into title (name, code,type) values ('FII OPPORTUN','FII OPPORTUN11','FII');
insert into title (name, code,type) values ('FII OURI JPP','FII OURI JPP11','FII');
insert into title (name, code,type) values ('FII OURO PRT','FII OURO PRT11','FII');
insert into title (name, code,type) values ('FII PANORAMA','FII PANORAMA11','FII');
insert into title (name, code,type) values ('FII LASTMILE','FII LASTMILE11','FII');
insert into title (name, code,type) values ('FII PAN PROP','FII PAN PROP11','FII');
insert into title (name, code,type) values ('FII PARK PAR','FII PARK PAR11','FII');
insert into title (name, code,type) values ('FII PARQ ANH','FII PARQ ANH11','FII');
insert into title (name, code,type) values ('FII PATRIA','FII PATRIA11','FII');
insert into title (name, code,type) values ('FII PATR LOG','FII PATR LOG11','FII');
insert into title (name, code,type) values ('FII PERFORMA','FII PERFORMA11','FII');
insert into title (name, code,type) values ('FII PERSONAL','FII PERSONAL11','FII');
insert into title (name, code,type) values ('FII PLURAL L','FII PLURAL L11','FII');
insert into title (name, code,type) values ('FII PLUR URB','FII PLUR URB11','FII');
insert into title (name, code,type) values ('FII POLO CRI','FII POLO CRI11','FII');
insert into title (name, code,type) values ('FII POLO I','FII POLO I11','FII');
insert into title (name, code,type) values ('FII PRAZO','FII PRAZO11','FII');
insert into title (name, code,type) values ('FII P VARGAS','FII P VARGAS11','FII');
insert into title (name, code,type) values ('FII PROLOGIS','FII PROLOGIS11','FII');
insert into title (name, code,type) values ('FII QUASAR A','FII QUASAR A11','FII');
insert into title (name, code,type) values ('FII QUASAR C','FII QUASAR C11','FII');
insert into title (name, code,type) values ('FII QUATA','FII QUATA11','FII');
insert into title (name, code,type) values ('FII RCAP FOF','FII RCAP FOF11','FII');
insert into title (name, code,type) values ('FII RBRESID3','FII RBRESID311','FII');
insert into title (name, code,type) values ('FII RBRESID2','FII RBRESID211','FII');
insert into title (name, code,type) values ('FII RBRES IV','FII RBRES IV11','FII');
insert into title (name, code,type) values ('FII RBCAP LG','FII RBCAP LG11','FII');
insert into title (name, code,type) values ('FII R INCOME','FII R INCOME11','FII');
insert into title (name, code,type) values ('FII RBCAP RI','FII RBCAP RI11','FII');
insert into title (name, code,type) values ('FII RB CAP I','FII RB CAP I11','FII');
insert into title (name, code,type) values ('FII RB II','FII RB II11','FII');
insert into title (name, code,type) values ('FII RB REN','FII RB REN11','FII');
insert into title (name, code,type) values ('FII RB TFO','FII RB TFO11','FII');
insert into title (name, code,type) values ('FII RBRALPHA','FII RBRALPHA11','FII');
insert into title (name, code,type) values ('FII RBR FEED','FII RBR FEED11','FII');
insert into title (name, code,type) values ('FII RBR LOG','FII RBR LOG11','FII');
insert into title (name, code,type) values ('FII RBR PR','FII RBR PR11','FII');
insert into title (name, code,type) values ('FII REAGMULT','FII REAGMULT11','FII');
insert into title (name, code,type) values ('FII RBCRI IV','FII RBCRI IV11','FII');
insert into title (name, code,type) values ('FII RB YIELD','FII RB YIELD11','FII');
insert into title (name, code,type) values ('FII RIOBCRI2','FII RIOBCRI211','FII');
insert into title (name, code,type) values ('FII RIOB FF','FII RIOB FF11','FII');
insert into title (name, code,type) values ('FII RIOB RR','FII RIOB RR11','FII');
insert into title (name, code,type) values ('FII RIZA AKN','FII RIZA AKN11','FII');
insert into title (name, code,type) values ('FII ARCTIUM','FII ARCTIUM11','FII');
insert into title (name, code,type) values ('FII SANT PAP','FII SANT PAP11','FII');
insert into title (name, code,type) values ('FII SANT REN','FII SANT REN11','FII');
insert into title (name, code,type) values ('FII S CARLOS','FII S CARLOS11','FII');
insert into title (name, code,type) values ('FII DOMINGOS','FII DOMINGOS11','FII');
insert into title (name, code,type) values ('FII SAO FRAN','FII SAO FRAN11','FII');
insert into title (name, code,type) values ('FII SEQUOIA','FII SEQUOIA11','FII');
insert into title (name, code,type) values ('FII SERRA VD','FII SERRA VD11','FII');
insert into title (name, code,type) values ('FII W PLAZA','FII W PLAZA11','FII');
insert into title (name, code,type) values ('FII SIG CAP','FII SIG CAP11','FII');
insert into title (name, code,type) values ('FII REIT RIV','FII REIT RIV11','FII');
insert into title (name, code,type) values ('FII SJ AU','FII SJ AU11','FII');
insert into title (name, code,type) values ('FII SOLARIUM','FII SOLARIUM11','FII');
insert into title (name, code,type) values ('FII SP DOWNT','FII SP DOWNT11','FII');
insert into title (name, code,type) values ('FII SPA','FII SPA11','FII');
insert into title (name, code,type) values ('FII STARX','FII STARX11','FII');
insert into title (name, code,type) values ('FII SUNOFOFI','FII SUNOFOFI11','FII');
insert into title (name, code,type) values ('FII SUNO CRI','FII SUNO CRI11','FII');
insert into title (name, code,type) values ('FII TELLUS','FII TELLUS11','FII');
insert into title (name, code,type) values ('FII TELF','FII TELF11','FII');
insert into title (name, code,type) values ('FII TEL PROP','FII TEL PROP11','FII');
insert into title (name, code,type) values ('FII TISHMAN','FII TISHMAN11','FII');
insert into title (name, code,type) values ('FII TJK REND','FII TJK REND11','FII');
insert into title (name, code,type) values ('FII TORDE EI','FII TORDE EI11','FII');
insert into title (name, code,type) values ('FII TRANSINC','FII TRANSINC11','FII');
insert into title (name, code,type) values ('FII TREECORP','FII TREECORP11','FII');
insert into title (name, code,type) values ('FII TRXE COR','FII TRXE COR11','FII');
insert into title (name, code,type) values ('FII TRX REAL','FII TRX REAL11','FII');
insert into title (name, code,type) values ('FII TRX R II','FII TRX R II11','FII');
insert into title (name, code,type) values ('FII TS NEW','FII TS NEW11','FII');
insert into title (name, code,type) values ('FII URCA REN','FII URCA REN11','FII');
insert into title (name, code,type) values ('FII VALREIII','FII VALREIII11','FII');
insert into title (name, code,type) values ('FII VALORAIP','FII VALORAIP11','FII');
insert into title (name, code,type) values ('FII VALOR HE','FII VALOR HE11','FII');
insert into title (name, code,type) values ('FII VBI CON','FII VBI CON11','FII');
insert into title (name, code,type) values ('FII VBI REIT','FII VBI REIT11','FII');
insert into title (name, code,type) values ('FII VECTIS','FII VECTIS11','FII');
insert into title (name, code,type) values ('FII VECT REN','FII VECT REN11','FII');
insert into title (name, code,type) values ('FII VQ LAJES','FII VQ LAJES11','FII');
insert into title (name, code,type) values ('FII VENUS','FII VENUS11','FII');
insert into title (name, code,type) values ('FII VERS CRI','FII VERS CRI11','FII');
insert into title (name, code,type) values ('FII VIC DES','FII VIC DES11','FII');
insert into title (name, code,type) values ('FII VINCI IU','FII VINCI IU11','FII');
insert into title (name, code,type) values ('FII VINCI IF','FII VINCI IF11','FII');
insert into title (name, code,type) values ('FII VINCI LG','FII VINCI LG11','FII');
insert into title (name, code,type) values ('FII VINCI OF','FII VINCI OF11','FII');
insert into title (name, code,type) values ('FII VINCI SC','FII VINCI SC11','FII');
insert into title (name, code,type) values ('FII V MASTER','FII V MASTER11','FII');
insert into title (name, code,type) values ('FII VX XVI','FII VX XVI11','FII');
insert into title (name, code,type) values ('FII WHG REAL','FII WHG REAL11','FII');
insert into title (name, code,type) values ('FII XP MACAE','FII XP MACAE11','FII');
insert into title (name, code,type) values ('FII XP CRED','FII XP CRED11','FII');
insert into title (name, code,type) values ('FII XP HOT','FII XP HOT11','FII');
insert into title (name, code,type) values ('FII XP INDL','FII XP INDL11','FII');
insert into title (name, code,type) values ('FII XP LOG','FII XP LOG11','FII');
insert into title (name, code,type) values ('FII XP MALLS','FII XP MALLS11','FII');
insert into title (name, code,type) values ('FII XP PROP','FII XP PROP11','FII');
insert into title (name, code,type) values ('FII XP SELEC','FII XP SELEC11','FII');
insert into title (name, code,type) values ('FII YUCA','FII YUCA11','FII');
insert into title (name, code,type) values ('FII ZION','FII ZION11','FII');