CREATE TABLE title (
	id INT NOT NULL AUTO_INCREMENT,
	name varchar(255) NOT NULL,
	code VARCHAR(20) NOT NULL,
	type VARCHAR(20) NOT NULL,
	PRIMARY KEY ( id )
);

insert into title (name, code,type) values ('3R PETROLEUM ON','RRRP3','ACTION');
insert into title (name, code,type) values ('3TENTOS ON','TTEN3','ACTION');
insert into title (name, code,type) values ('ABC BRASIL PN','ABCB4','ACTION');
insert into title (name, code,type) values ('ADOBE INC DRN','ADBE34','ACTION');
insert into title (name, code,type) values ('ADVANCED MIC DRN','A1MD34','ACTION');
insert into title (name, code,type) values ('AERIS ON','AERI3','ACTION');
insert into title (name, code,type) values ('AES BRASIL ON','AESB3','ACTION');
insert into title (name, code,type) values ('AGROGALAXY ON','AGXY3','ACTION');
insert into title (name, code,type) values ('AIRBNB DRN','AIRB34','ACTION');
insert into title (name, code,type) values ('ALIANSCSONAE ON','ALSO3','ACTION');
insert into title (name, code,type) values ('ALIBABAGR DRN','BABA34','ACTION');
insert into title (name, code,type) values ('ALLIAR ON','AALR3','ACTION');
insert into title (name, code,type) values ('ALLIED ON','ALLD3','ACTION');
insert into title (name, code,type) values ('ALPARGATAS PN','ALPA4','ACTION');
insert into title (name, code,type) values ('ALPHABET DRN A','GOGL34','ACTION');
insert into title (name, code,type) values ('ALUPAR UNT','ALUP11','ACTION');
insert into title (name, code,type) values ('AMAZON DRN','AMZO34','ACTION');
insert into title (name, code,type) values ('AMBEV S/A ON','ABEV3','ACTION');
insert into title (name, code,type) values ('AMBIPAR ON','AMBP3','ACTION');
insert into title (name, code,type) values ('AMERICAN AIR DRN','AALL34','ACTION');
insert into title (name, code,type) values ('AMERICANAS ON','AMER3','ACTION');
insert into title (name, code,type) values ('ANIMA ON','ANIM3','ACTION');
insert into title (name, code,type) values ('APPLE DRN','AAPL34','ACTION');
insert into title (name, code,type) values ('AREZZO CO ON','ARZZ3','ACTION');
insert into title (name, code,type) values ('ARMAC ON','ARML3','ACTION');
insert into title (name, code,type) values ('ASSAI ON','ASAI3','ACTION');
insert into title (name, code,type) values ('AURA 360 DR3','AURA33','ACTION');
insert into title (name, code,type) values ('AZUL PN','AZUL4','ACTION');
insert into title (name, code,type) values ('B3 ON','B3SA3','ACTION');
insert into title (name, code,type) values ('BANCO BMG PN','BMGB4','ACTION');
insert into title (name, code,type) values ('BANCO INTER ON EJ','BIDI3','ACTION');
insert into title (name, code,type) values ('BANCO INTER PN EJ','BIDI4','ACTION');
insert into title (name, code,type) values ('BANCO INTER UNT EJ','BIDI11','ACTION');
insert into title (name, code,type) values ('BANCO PAN PN','BPAN4','ACTION');
insert into title (name, code,type) values ('BANK AMERICA DRN ED','BOAC34','ACTION');
insert into title (name, code,type) values ('BANRISUL PNB','BRSR6','ACTION');
insert into title (name, code,type) values ('BBSEGURIDADE ON','BBSE3','ACTION');
insert into title (name, code,type) values ('BEMOBI TECH ON','BMOB3','ACTION');
insert into title (name, code,type) values ('BERKSHIRE DRN','BERK34','ACTION');
insert into title (name, code,type) values ('BIONTECH SE DRN','B1NT34','ACTION');
insert into title (name, code,type) values ('BITCOIN HASH CI','BITH11','ACTION');
insert into title (name, code,type) values ('BK BRASIL ON','BKBR3','ACTION');
insert into title (name, code,type) values ('BLAU ON','BLAU3','ACTION');
insert into title (name, code,type) values ('BOA SAFRA ON','SOJA3','ACTION');
insert into title (name, code,type) values ('BOA VISTA ON','BOAS3','ACTION');
insert into title (name, code,type) values ('BOOKING DRN','BKNG34','ACTION');
insert into title (name, code,type) values ('BR BROKERS ON','BBRK3','ACTION');
insert into title (name, code,type) values ('BR MALLS PAR ON','BRML3','ACTION');
insert into title (name, code,type) values ('BR PARTNERS UNT','BRBI11','ACTION');
insert into title (name, code,type) values ('BR PROPERT ON','BRPR3','ACTION');
insert into title (name, code,type) values ('BRADESCO ON EJ','BBDC3','ACTION');
insert into title (name, code,type) values ('BRADESCO PN EJ','BBDC4','ACTION');
insert into title (name, code,type) values ('BRADESPAR ON','BRAP3','ACTION');
insert into title (name, code,type) values ('BRADESPAR PN','BRAP4','ACTION');
insert into title (name, code,type) values ('BRASIL ON EX','BBAS3','ACTION');
insert into title (name, code,type) values ('BRASILAGRO ON','AGRO3','ACTION');
insert into title (name, code,type) values ('BRASKEM PNA','BRKM5','ACTION');
insert into title (name, code,type) values ('BRF SA ON','BRFS3','ACTION');
insert into title (name, code,type) values ('BRISANET ON','BRIT3','ACTION');
insert into title (name, code,type) values ('BTGP BANCO UNT','BPAC11','ACTION');
insert into title (name, code,type) values ('CAIXA SEGURI ON','CXSE3','ACTION');
insert into title (name, code,type) values ('CAMIL ON EJ','CAML3','ACTION');
insert into title (name, code,type) values ('CARREFOUR BR ON','CRFB3','ACTION');
insert into title (name, code,type) values ('CBA ON','CBAV3','ACTION');
insert into title (name, code,type) values ('CCR SA ON','CCRO3','ACTION');
insert into title (name, code,type) values ('CEA MODAS ON','CEAB3','ACTION');
insert into title (name, code,type) values ('CEMIG ON','CMIG3','ACTION');
insert into title (name, code,type) values ('CEMIG PN','CMIG4','ACTION');
insert into title (name, code,type) values ('CESP PNB','CESP6','ACTION');
insert into title (name, code,type) values ('CHEVRON DRN','CHVX34','ACTION');
insert into title (name, code,type) values ('CIELO ON','CIEL3','ACTION');
insert into title (name, code,type) values ('CLEARSALE ON','CLSA3','ACTION');
insert into title (name, code,type) values ('COCA COLA DRN','COCA34','ACTION');
insert into title (name, code,type) values ('COGNA ON ON','COGN3','ACTION');
insert into title (name, code,type) values ('COMCAST DRN','CMCS34','ACTION');
insert into title (name, code,type) values ('COPASA ON','CSMG3','ACTION');
insert into title (name, code,type) values ('COPEL ON','CPLE3','ACTION');
insert into title (name, code,type) values ('COPEL PNB','CPLE6','ACTION');
insert into title (name, code,type) values ('COPEL UNT','CPLE11','ACTION');
insert into title (name, code,type) values ('COREMSCI EUR DRN','BIEU39','ACTION');
insert into title (name, code,type) values ('COSAN ON','CSAN3','ACTION');
insert into title (name, code,type) values ('COSTCO DRN','COWC34','ACTION');
insert into title (name, code,type) values ('CPFL ENERGIA ON','CPFE3','ACTION');
insert into title (name, code,type) values ('CRUZEIRO EDU ON','CSED3','ACTION');
insert into title (name, code,type) values ('CSNMINERACAO ON','CMIN3','ACTION');
insert into title (name, code,type) values ('CSU CARDSYST ON','CARD3','ACTION');
insert into title (name, code,type) values ('CURY S/A ON','CURY3','ACTION');
insert into title (name, code,type) values ('CVC BRASIL ON','CVCB3','ACTION');
insert into title (name, code,type) values ('CYRELA REALT ON','CYRE3','ACTION');
insert into title (name, code,type) values ('DASA ON','DASA3','ACTION');
insert into title (name, code,type) values ('DESKTOP ON','DESK3','ACTION');
insert into title (name, code,type) values ('DEXCO ON','DXCO3','ACTION');
insert into title (name, code,type) values ('DEXXOS PAR ON','DEXP3','ACTION');
insert into title (name, code,type) values ('DIMED ON','PNVL3','ACTION');
insert into title (name, code,type) values ('DIRECIONAL ON','DIRR3','ACTION');
insert into title (name, code,type) values ('DOMMO ON','DMMO3','ACTION');
insert into title (name, code,type) values ('ECORODOVIAS ON','ECOR3','ACTION');
insert into title (name, code,type) values ('ELETROBRAS ON','ELET3','ACTION');
insert into title (name, code,type) values ('ELETROBRAS PNB','ELET6','ACTION');
insert into title (name, code,type) values ('ELETROMIDIA ON','ELMD3','ACTION');
insert into title (name, code,type) values ('EMBRAER ON','EMBR3','ACTION');
insert into title (name, code,type) values ('ENAUTA PART ON','ENAT3','ACTION');
insert into title (name, code,type) values ('ENERGIAS BR ON','ENBR3','ACTION');
insert into title (name, code,type) values ('ENERGISA UNT','ENGI11','ACTION');
insert into title (name, code,type) values ('ENEVA ON','ENEV3','ACTION');
insert into title (name, code,type) values ('ENGIE BRASIL ON','EGIE3','ACTION');
insert into title (name, code,type) values ('ENJOEI ON','ENJU3','ACTION');
insert into title (name, code,type) values ('EQUATORIAL ON','EQTL3','ACTION');
insert into title (name, code,type) values ('ESPACOLASER ON','ESPA3','ACTION');
insert into title (name, code,type) values ('ETERNIT ON','ETER3','ACTION');
insert into title (name, code,type) values ('ETF BRA IBOV CI','BOVB11','ACTION');
insert into title (name, code,type) values ('ETHER HASH CI','ETHE11','ACTION');
insert into title (name, code,type) values ('EVEN ON','EVEN3','ACTION');
insert into title (name, code,type) values ('EXXON MOBIL DRN','EXXO34','ACTION');
insert into title (name, code,type) values ('EZTEC ON','EZTC3','ACTION');
insert into title (name, code,type) values ('FER HERINGER ON','FHER3','ACTION');
insert into title (name, code,type) values ('FERBASA PN','FESA4','ACTION');
insert into title (name, code,type) values ('FIAGRO RIZA CI ER','RZAG11','ACTION');
insert into title (name, code,type) values ('FINAM CI *','FNAM11','ACTION');
insert into title (name, code,type) values ('FINOR CI *','FNOR11','ACTION');
insert into title (name, code,type) values ('FLEURY ON','FLRY3','ACTION');
insert into title (name, code,type) values ('FOCUS ON ON','POWE3','ACTION');
insert into title (name, code,type) values ('FRAS-LE ON','FRAS3','ACTION');
insert into title (name, code,type) values ('GAFISA ON','GFSA3','ACTION');
insert into title (name, code,type) values ('GENERAL MOT DRN','GMCO34','ACTION');
insert into title (name, code,type) values ('GERDAU ON ED','GGBR3','ACTION');
insert into title (name, code,type) values ('GERDAU PN ED','GGBR4','ACTION');
insert into title (name, code,type) values ('GERDAU MET ON ED','GOAU3','ACTION');
insert into title (name, code,type) values ('GERDAU MET PN ED','GOAU4','ACTION');
insert into title (name, code,type) values ('GETNET BR UNT','GETT11','ACTION');
insert into title (name, code,type) values ('GETNINJAS ON','NINJ3','ACTION');
insert into title (name, code,type) values ('GOL PN','GOLL4','ACTION');
insert into title (name, code,type) values ('GOLD TRUST DRN','BIAU39','ACTION');
insert into title (name, code,type) values ('GPS ON','GGPS3','ACTION');
insert into title (name, code,type) values ('GRENDENE ON','GRND3','ACTION');
insert into title (name, code,type) values ('GRUPO MATEUS ON','GMAT3','ACTION');
insert into title (name, code,type) values ('GRUPO NATURA ON','NTCO3','ACTION');
insert into title (name, code,type) values ('GRUPO SBF ON','SBFG3','ACTION');
insert into title (name, code,type) values ('GRUPO SOMA ON','SOMA3','ACTION');
insert into title (name, code,type) values ('GUARARAPES ON','GUAR3','ACTION');
insert into title (name, code,type) values ('HAPVIDA ON','HAPV3','ACTION');
insert into title (name, code,type) values ('HASHDEX NCI CI','HASH11','ACTION');
insert into title (name, code,type) values ('HELBOR ON','HBOR3','ACTION');
insert into title (name, code,type) values ('HIDROVIAS ON','HBSA3','ACTION');
insert into title (name, code,type) values ('HOME DEPOT DRN ED','HOME34','ACTION');
insert into title (name, code,type) values ('HYPERA ON','HYPE3','ACTION');
insert into title (name, code,type) values ('IGUATEMI S.A ON','IGTI3','ACTION');
insert into title (name, code,type) values ('IGUATEMI S.A UNT','IGTI11','ACTION');
insert into title (name, code,type) values ('IHPARDINI ON','PARD3','ACTION');
insert into title (name, code,type) values ('IMC S/A ON','MEAL3','ACTION');
insert into title (name, code,type) values ('INDS ROMI ON','ROMI3','ACTION');
insert into title (name, code,type) values ('INEPAR ON','INEP3','ACTION');
insert into title (name, code,type) values ('INFRACOMM ON','IFCM3','ACTION');
insert into title (name, code,type) values ('INTELBRAS ON ED','INTB3','ACTION');
insert into title (name, code,type) values ('INVESTO JOGO CI','JOGO11','ACTION');
insert into title (name, code,type) values ('IOCHP-MAXION ON','MYPK3','ACTION');
insert into title (name, code,type) values ('IRANI ON ED','RANI3','ACTION');
insert into title (name, code,type) values ('IRBBRASIL RE ON','IRBR3','ACTION');
insert into title (name, code,type) values ('ISHARE SP500 CI','IVVB11','ACTION');
insert into title (name, code,type) values ('ISHARES BOVA CI','BOVA11','ACTION');
insert into title (name, code,type) values ('ISHARES SMAL CI','SMAL11','ACTION');
insert into title (name, code,type) values ('IT NOW IBOV CI','BOVV11','ACTION');
insert into title (name, code,type) values ('IT NOW IDIV CI','DIVO11','ACTION');
insert into title (name, code,type) values ('IT NOW IFNC CI','FIND11','ACTION');
insert into title (name, code,type) values ('IT NOW IMA-B F11','IMAB11','ACTION');
insert into title (name, code,type) values ('IT NOW IMAT CI','MATB11','ACTION');
insert into title (name, code,type) values ('IT NOW PIBB CI','PIBB11','ACTION');
insert into title (name, code,type) values ('IT NOW SMALL CI','SMAC11','ACTION');
insert into title (name, code,type) values ('IT NOW SPXI CI','SPXI11','ACTION');
insert into title (name, code,type) values ('ITAUSA ON','ITSA3','ACTION');
insert into title (name, code,type) values ('ITAUSA PN','ITSA4','ACTION');
insert into title (name, code,type) values ('ITAUUNIBANCO ON EJ','ITUB3','ACTION');
insert into title (name, code,type) values ('ITAUUNIBANCO PN EJ','ITUB4','ACTION');
insert into title (name, code,type) values ('JALLESMACHAD ON','JALL3','ACTION');
insert into title (name, code,type) values ('JBS ON','JBSS3','ACTION');
insert into title (name, code,type) values ('JHSF PART ON ED','JHSF3','ACTION');
insert into title (name, code,type) values ('JOHNSON DRN','JNJB34','ACTION');
insert into title (name, code,type) values ('JPMORGAN DRN','JPMC34','ACTION');
insert into title (name, code,type) values ('JSL ON','JSLG3','ACTION');
insert into title (name, code,type) values ('KEPLER WEBER ON','KEPL3','ACTION');
insert into title (name, code,type) values ('KINEA INFRAF FIDCER','KDIF11','ACTION');
insert into title (name, code,type) values ('KLABIN S/A PN','KLBN4','ACTION');
insert into title (name, code,type) values ('KLABIN S/A UNT','KLBN11','ACTION');
insert into title (name, code,type) values ('LAVVI ON','LAVV3','ACTION');
insert into title (name, code,type) values ('LIGHT S/A ON','LIGT3','ACTION');
insert into title (name, code,type) values ('LOCALIZA ON','RENT3','ACTION');
insert into title (name, code,type) values ('LOCAMERICA ON','LCAM3','ACTION');
insert into title (name, code,type) values ('LOCAWEB ON','LWSA3','ACTION');
insert into title (name, code,type) values ('LOG COM PROP ON','LOGG3','ACTION');
insert into title (name, code,type) values ('LOG-IN ON','LOGN3','ACTION');
insert into title (name, code,type) values ('LOJAS MARISA ON','AMAR3','ACTION');
insert into title (name, code,type) values ('LOJAS RENNER ON','LREN3','ACTION');
insert into title (name, code,type) values ('LOPES BRASIL ON','LPSB3','ACTION');
insert into title (name, code,type) values ('LUPATECH ON','LUPA3','ACTION');
insert into title (name, code,type) values ('M.DIASBRANCO ON','MDIA3','ACTION');
insert into title (name, code,type) values ('MAGAZ LUIZA ON','MGLU3','ACTION');
insert into title (name, code,type) values ('MARCOPOLO PN','POMO4','ACTION');
insert into title (name, code,type) values ('MARFRIG ON','MRFG3','ACTION');
insert into title (name, code,type) values ('MASTERCARD DRN','MSCD34','ACTION');
insert into title (name, code,type) values ('MATER DEI ON','MATD3','ACTION');
insert into title (name, code,type) values ('MCDONALDS DRN','MCDC34','ACTION');
insert into title (name, code,type) values ('MELIUZ ON','CASH3','ACTION');
insert into title (name, code,type) values ('MELNICK ON','MELK3','ACTION');
insert into title (name, code,type) values ('MERCADOLIBRE DRN','MELI34','ACTION');
insert into title (name, code,type) values ('META PLAT DRN','FBOK34','ACTION');
insert into title (name, code,type) values ('METAL LEVE ON','LEVE3','ACTION');
insert into title (name, code,type) values ('MICRON TECHN DRN','MUTC34','ACTION');
insert into title (name, code,type) values ('MICROSOFT DRN','MSFT34','ACTION');
insert into title (name, code,type) values ('MILLS ON','MILS3','ACTION');
insert into title (name, code,type) values ('MINERVA ON','BEEF3','ACTION');
insert into title (name, code,type) values ('MITRE REALTY ON ED','MTRE3','ACTION');
insert into title (name, code,type) values ('MOBLY ON','MBLY3','ACTION');
insert into title (name, code,type) values ('MODALMAIS UNT','MODL11','ACTION');
insert into title (name, code,type) values ('MODERNA INC DRN','M1RN34','ACTION');
insert into title (name, code,type) values ('MOSAICO ON','MOSI3','ACTION');
insert into title (name, code,type) values ('MOURA DUBEUX ON','MDNE3','ACTION');
insert into title (name, code,type) values ('MOVIDA ON','MOVI3','ACTION');
insert into title (name, code,type) values ('MRV ON','MRVE3','ACTION');
insert into title (name, code,type) values ('MSCI ACWI DRN','BACW39','ACTION');
insert into title (name, code,type) values ('MULTILASER ON','MLAS3','ACTION');
insert into title (name, code,type) values ('MULTIPLAN ON','MULT3','ACTION');
insert into title (name, code,type) values ('NEOENERGIA ON','NEOE3','ACTION');
insert into title (name, code,type) values ('NEOGRID ON','NGRD3','ACTION');
insert into title (name, code,type) values ('NETFLIX DRN','NFLX34','ACTION');
insert into title (name, code,type) values ('NIKE DRN ED','NIKE34','ACTION');
insert into title (name, code,type) values ('NU-NUBANK DR3','NUBR33','ACTION');
insert into title (name, code,type) values ('NVIDIA CORP DRN ED','NVDC34','ACTION');
insert into title (name, code,type) values ('OCCIDENT PTR DRN ED','OXYP34','ACTION');
insert into title (name, code,type) values ('OCEANPACT ON','OPCT3','ACTION');
insert into title (name, code,type) values ('ODONTOPREV ON','ODPV3','ACTION');
insert into title (name, code,type) values ('OI ON ES','OIBR3','ACTION');
insert into title (name, code,type) values ('OI PN ES','OIBR4','ACTION');
insert into title (name, code,type) values ('OMEGAENERGIA ON','MEGA3','ACTION');
insert into title (name, code,type) values ('ONCOCLINICAS ON','ONCO3','ACTION');
insert into title (name, code,type) values ('ORIZON ON','ORVR3','ACTION');
insert into title (name, code,type) values ('P.ACUCAR-CBD ON','PCAR3','ACTION');
insert into title (name, code,type) values ('PAGUE MENOS ON','PGMN3','ACTION');
insert into title (name, code,type) values ('PARANAPANEMA ON','PMAM3','ACTION');
insert into title (name, code,type) values ('PAYPAL HOLD DRN','PYPL34','ACTION');
insert into title (name, code,type) values ('PETROBRAS ON','PETR3','ACTION');
insert into title (name, code,type) values ('PETROBRAS PN','PETR4','ACTION');
insert into title (name, code,type) values ('PETRORECSA ON','RECV3','ACTION');
insert into title (name, code,type) values ('PETRORIO ON','PRIO3','ACTION');
insert into title (name, code,type) values ('PETZ ON','PETZ3','ACTION');
insert into title (name, code,type) values ('PFIZER DRN','PFIZ34','ACTION');
insert into title (name, code,type) values ('PG DRN','PGCO34','ACTION');
insert into title (name, code,type) values ('PLANOEPLANO ON','PLPL3','ACTION');
insert into title (name, code,type) values ('PORTO SEGURO ON','PSSA3','ACTION');
insert into title (name, code,type) values ('PORTOBELLO ON','PTBL3','ACTION');
insert into title (name, code,type) values ('POSITIVO TEC ON','POSI3','ACTION');
insert into title (name, code,type) values ('QR BITCOIN CI','QBTC11','ACTION');
insert into title (name, code,type) values ('QR ETHER CI','QETH11','ACTION');
insert into title (name, code,type) values ('QUALICORP ON','QUAL3','ACTION');
insert into title (name, code,type) values ('QUERO-QUERO ON','LJQQ3','ACTION');
insert into title (name, code,type) values ('RAIADROGASIL ON','RADL3','ACTION');
insert into title (name, code,type) values ('RAIZEN PN','RAIZ4','ACTION');
insert into title (name, code,type) values ('RANDON PART PN','RAPT4','ACTION');
insert into title (name, code,type) values ('RECRUSUL ON','RCSL3','ACTION');
insert into title (name, code,type) values ('REDE D OR ON','RDOR3','ACTION');
insert into title (name, code,type) values ('RUMO S.A. ON','RAIL3','ACTION');
insert into title (name, code,type) values ('SABESP ON','SBSP3','ACTION');
insert into title (name, code,type) values ('SALESFORCE DRN','SSFO34','ACTION');
insert into title (name, code,type) values ('SANEPAR ON','SAPR3','ACTION');
insert into title (name, code,type) values ('SANEPAR PN','SAPR4','ACTION');
insert into title (name, code,type) values ('SANEPAR UNT','SAPR11','ACTION');
insert into title (name, code,type) values ('SANTANDER BR ON','SANB3','ACTION');
insert into title (name, code,type) values ('SANTANDER BR PN','SANB4','ACTION');
insert into title (name, code,type) values ('SANTANDER BR UNT','SANB11','ACTION');
insert into title (name, code,type) values ('SANTOS BRP ON','STBP3','ACTION');
insert into title (name, code,type) values ('SAO MARTINHO ON','SMTO3','ACTION');
insert into title (name, code,type) values ('SCHULZ PN','SHUL4','ACTION');
insert into title (name, code,type) values ('SEQUOIA LOG ON','SEQL3','ACTION');
insert into title (name, code,type) values ('SER EDUCA ON','SEER3','ACTION');
insert into title (name, code,type) values ('SID NACIONAL ON','CSNA3','ACTION');
insert into title (name, code,type) values ('SIMPAR ON','SIMH3','ACTION');
insert into title (name, code,type) values ('SINQIA ON','SQIA3','ACTION');
insert into title (name, code,type) values ('SLC AGRICOLA ON','SLCE3','ACTION');
insert into title (name, code,type) values ('SMART FIT ON','SMFT3','ACTION');
insert into title (name, code,type) values ('SP500 VALUE DRN','BIVE39','ACTION');
insert into title (name, code,type) values ('SUL AMERICA UNT','SULA11','ACTION');
insert into title (name, code,type) values ('SUZANO S.A. ON','SUZB3','ACTION');
insert into title (name, code,type) values ('SYN PROP TEC ON','SYNE3','ACTION');
insert into title (name, code,type) values ('TAESA ON','TAEE3','ACTION');
insert into title (name, code,type) values ('TAESA PN','TAEE4','ACTION');
insert into title (name, code,type) values ('TAESA UNT','TAEE11','ACTION');
insert into title (name, code,type) values ('TAIWANSMFAC DRN','TSMC34','ACTION');
insert into title (name, code,type) values ('TAURUS ARMAS PN','TASA4','ACTION');
insert into title (name, code,type) values ('TC ON','TRAD3','ACTION');
insert into title (name, code,type) values ('TECHNOS ON','TECN3','ACTION');
insert into title (name, code,type) values ('TECNISA ON','TCSA3','ACTION');
insert into title (name, code,type) values ('TEGMA ON','TGMA3','ACTION');
insert into title (name, code,type) values ('TELEF BRASIL ON EJ','VIVT3','ACTION');
insert into title (name, code,type) values ('TENDA ON','TEND3','ACTION');
insert into title (name, code,type) values ('TESLA INC DRN','TSLA34','ACTION');
insert into title (name, code,type) values ('TIM ON','TIMS3','ACTION');
insert into title (name, code,type) values ('TIME FOR FUN ON','SHOW3','ACTION');
insert into title (name, code,type) values ('TOTVS ON','TOTS3','ACTION');
insert into title (name, code,type) values ('TRAN PAULIST PN','TRPL4','ACTION');
insert into title (name, code,type) values ('TREND ACWI CI','ACWI11','ACTION');
insert into title (name, code,type) values ('TREND CHINA CI','XINA11','ACTION');
insert into title (name, code,type) values ('TREND ESG D CI','ESGD11','ACTION');
insert into title (name, code,type) values ('TREND ESG US CI','ESGU11','ACTION');
insert into title (name, code,type) values ('TREND EUROPA CI','EURP11','ACTION');
insert into title (name, code,type) values ('TREND IBOVX CI','BOVX11','ACTION');
insert into title (name, code,type) values ('TREND NASDAQ CI','NASD11','ACTION');
insert into title (name, code,type) values ('TREND OURO CI','GOLD11','ACTION');
insert into title (name, code,type) values ('TREND US LRG CI','USAL11','ACTION');
insert into title (name, code,type) values ('TRISUL ON','TRIS3','ACTION');
insert into title (name, code,type) values ('TRUSTMSCI US DRN','BEGU39','ACTION');
insert into title (name, code,type) values ('TUPY ON','TUPY3','ACTION');
insert into title (name, code,type) values ('UBER TECH IN DRN','U1BE34','ACTION');
insert into title (name, code,type) values ('ULTRAPAR ON ED','UGPA3','ACTION');
insert into title (name, code,type) values ('UNIFIQUE ON','FIQE3','ACTION');
insert into title (name, code,type) values ('UNIPAR ON','UNIP3','ACTION');
insert into title (name, code,type) values ('UNIPAR PNB','UNIP6','ACTION');
insert into title (name, code,type) values ('UNITEDHEALTH DRN ED','UNHH34','ACTION');
insert into title (name, code,type) values ('USIMINAS ON','USIM3','ACTION');
insert into title (name, code,type) values ('USIMINAS PNA','USIM5','ACTION');
insert into title (name, code,type) values ('VALE ON ED','VALE3','ACTION');
insert into title (name, code,type) values ('VALID ON','VLID3','ACTION');
insert into title (name, code,type) values ('VAMOS ON','VAMO3','ACTION');
insert into title (name, code,type) values ('VIA ON','VIIA3','ACTION');
insert into title (name, code,type) values ('VIBRA ON','VBBR3','ACTION');
insert into title (name, code,type) values ('VISA INC DRN','VISA34','ACTION');
insert into title (name, code,type) values ('VITTIA ON','VITT3','ACTION');
insert into title (name, code,type) values ('VIVARA S.A. ON','VIVA3','ACTION');
insert into title (name, code,type) values ('VIVEO ON','VVEO3','ACTION');
insert into title (name, code,type) values ('VIVER ON','VIVR3','ACTION');
insert into title (name, code,type) values ('VULCABRAS ON','VULC3','ACTION');
insert into title (name, code,type) values ('WALT DISNEY DRN','DISB34','ACTION');
insert into title (name, code,type) values ('WDC NETWORKS ON','LVTC3','ACTION');
insert into title (name, code,type) values ('WEG ON','WEGE3','ACTION');
insert into title (name, code,type) values ('WELLS FARGO DRN','WFCO34','ACTION');
insert into title (name, code,type) values ('WESTWING ON','WEST3','ACTION');
insert into title (name, code,type) values ('WILSON SONS ON','PORT3','ACTION');
insert into title (name, code,type) values ('WIZ S.A. ON','WIZS3','ACTION');
insert into title (name, code,type) values ('XP INC DR1','XPBR31','ACTION');
insert into title (name, code,type) values ('YDUQS PART ON','YDUQ3','ACTION');
insert into title (name, code,type) values ('FII INTER IT','ITIT11','FII');
insert into title (name, code,type) values ('FII LAVOURA','LAVF11','FII');
insert into title (name, code,type) values ('FII AFHI CRI','AFHI11','FII');
insert into title (name, code,type) values ('FII ALIANZFF','AFOF11','FII');
insert into title (name, code,type) values ('FII MULT OF1','MTOF11','FII');
insert into title (name, code,type) values ('FII ALIANZA','ALZR11','FII');
insert into title (name, code,type) values ('FII AUTONOMY','AIEC11','FII');
insert into title (name, code,type) values ('FII BEES CRI','BCRI11','FII');
insert into title (name, code,type) values ('FII BANRISUL','BNFS11','FII');
insert into title (name, code,type) values ('FII BARZEL','BZEL11','FII');
insert into title (name, code,type) values ('FII BASILICA','BPLC11','FII');
insert into title (name, code,type) values ('FII BB PROGR','BBFI11','FII');
insert into title (name, code,type) values ('FII BB FOF','BBFO11','FII');
insert into title (name, code,type) values ('FII BB PRGII','BBPO11','FII');
insert into title (name, code,type) values ('FII BB RECIM','BBIM11','FII');
insert into title (name, code,type) values ('FII BB CORP','BBRC11','FII');
insert into title (name, code,type) values ('FII BB PAPII','RDPD11','FII');
insert into title (name, code,type) values ('FII BB R PAP','RNDP11','FII');
insert into title (name, code,type) values ('FII BLUECAP','BLCP11','FII');
insert into title (name, code,type) values ('FII BLUE AAA','BLCA11','FII');
insert into title (name, code,type) values ('FII BLUE CRI','BLMC11','FII');
insert into title (name, code,type) values ('FII BLUE LOG','BLMG11','FII');
insert into title (name, code,type) values ('FII BLUEMAC','BLMO11','FII');
insert into title (name, code,type) values ('FII BLUE FOF','BLMR11','FII');
insert into title (name, code,type) values ('FII BR PROPE','BROL11','FII');
insert into title (name, code,type) values ('FII BCIA','BCIA11','FII');
insert into title (name, code,type) values ('FII BRE VIC','BREV11','FII');
insert into title (name, code,type) values ('FII BRREALTY','BZLI11','FII');
insert into title (name, code,type) values ('FII DEA CARE','CARE11','FII');
insert into title (name, code,type) values ('FII BRESCO','BRCO11','FII');
insert into title (name, code,type) values ('FII BRIO CRE','BICE11','FII');
insert into title (name, code,type) values ('FII BRIO ME','BIME11','FII');
insert into title (name, code,type) values ('FII BRIO II','BRIM11','FII');
insert into title (name, code,type) values ('FII BRIO III','BRIP11','FII');
insert into title (name, code,type) values ('FII BRIO IV','BIPD11','FII');
insert into title (name, code,type) values ('FII BS2','LLAO11','FII');
insert into title (name, code,type) values ('FII BTLG','BTLG11','FII');
insert into title (name, code,type) values ('FII BTOWERS','BTWR11','FII');
insert into title (name, code,type) values ('FII BTSP I','BTSG11','FII');
insert into title (name, code,type) values ('FII BTSP II','BTSI11','FII');
insert into title (name, code,type) values ('FII CX RBRA2','CRFF11','FII');
insert into title (name, code,type) values ('FII CX RBRAV','CXRI11','FII');
insert into title (name, code,type) values ('FII CANVAS','CCRF11','FII');
insert into title (name, code,type) values ('FII CAP REIT','CPFF11','FII');
insert into title (name, code,type) values ('FII CAPI SEC','CPTS11','FII');
insert into title (name, code,type) values ('CARTESIA FII','CACR11','FII');
insert into title (name, code,type) values ('FII C BRANCO','CBOP11','FII');
insert into title (name, code,type) values ('FII CF2','CFHI11','FII');
insert into title (name, code,type) values ('FII CJCTOWER','CJCT11','FII');
insert into title (name, code,type) values ('FII CORE MET','CORM11','FII');
insert into title (name, code,type) values ('FII CSHG FOF','HGFF11','FII');
insert into title (name, code,type) values ('FII CSHG LOG','HGLG11','FII');
insert into title (name, code,type) values ('FII CSHGPRIM','HGPO11','FII');
insert into title (name, code,type) values ('FII HG REAL','HGRE11','FII');
insert into title (name, code,type) values ('FII CSHG CRI','HGCR11','FII');
insert into title (name, code,type) values ('FII CSHG URB','HGRU11','FII');
insert into title (name, code,type) values ('FII CSHG RSD','HGRS11','FII');
insert into title (name, code,type) values ('FII CVPAR','CVPR11','FII');
insert into title (name, code,type) values ('FII CYRELA','CYCR11','FII');
insert into title (name, code,type) values ('FII DEL MONT','DLMT11','FII');
insert into title (name, code,type) values ('FII DEVANT','DEVA11','FII');
insert into title (name, code,type) values ('FII DIAMANTE','DAMT11','FII');
insert into title (name, code,type) values ('FII DOVEL','DOVL11','FII');
insert into title (name, code,type) values ('FII ENERGY','EGYR11','FII');
insert into title (name, code,type) values ('FII EQI RECE','EQIR11','FII');
insert into title (name, code,type) values ('FII ESTOQ RJ','ERCR11','FII');
insert into title (name, code,type) values ('FII EUROPA','ERPA11','FII');
insert into title (name, code,type) values ('FII EVEN II','KEVE11','FII');
insert into title (name, code,type) values ('FII EV KINEA','KINP11','FII');
insert into title (name, code,type) values ('FII EXES','EXES11','FII');
insert into title (name, code,type) values ('FII FL RECEB','FLCR11','FII');
insert into title (name, code,type) values ('FII FATOR VE','VRTA11','FII');
insert into title (name, code,type) values ('FII BRASILIO','BMII11','FII');
insert into title (name, code,type) values ('FII LEBLON','LRDI11','FII');
insert into title (name, code,type) values ('FII MAUA HY','MCHY11','FII');
insert into title (name, code,type) values ('FII MAUA MPD','MMPD11','FII');
insert into title (name, code,type) values ('FII BREI','IBCR11','FII');
insert into title (name, code,type) values ('FII GUARD MU','GAME11','FII');
insert into title (name, code,type) values ('FII BTG CRI','BTCR11','FII');
insert into title (name, code,type) values ('FII MTRS','MTRS11','FII');
insert into title (name, code,type) values ('FII ANCAR IC','ANCR11','FII');
insert into title (name, code,type) values ('FII ANH EDUC','FAED11','FII');
insert into title (name, code,type) values ('FII BMBRC LC','BMLC11','FII');
insert into title (name, code,type) values ('FII BRLPROP','BPRP11','FII');
insert into title (name, code,type) values ('FII BC FUND','BRCR11','FII');
insert into title (name, code,type) values ('FII EXCELLEN','FEXC11','FII');
insert into title (name, code,type) values ('FII BC FFII','BCFF11','FII');
insert into title (name, code,type) values ('FII CAMPUSFL','FCFL11','FII');
insert into title (name, code,type) values ('FII CENESP','CNES11','FII');
insert into title (name, code,type) values ('FII CEO CCP','CEOC11','FII');
insert into title (name, code,type) values ('FII ALMIRANT','FAMB11','FII');
insert into title (name, code,type) values ('FII GALERIA','EDGA11','FII');
insert into title (name, code,type) values ('FII ELDORADO','ELDO11','FII');
insert into title (name, code,type) values ('FII FLORIPA','FLRP11','FII');
insert into title (name, code,type) values ('FII CRIANCA','HCRI11','FII');
insert into title (name, code,type) values ('FII LOURDES','NSLU11','FII');
insert into title (name, code,type) values ('FII HOTEL MX','HTMX11','FII');
insert into title (name, code,type) values ('FII MAX RET','MAXR11','FII');
insert into title (name, code,type) values ('FII NOVOHORI','NVHO11','FII');
insert into title (name, code,type) values ('FII D PEDRO','PQDP11','FII');
insert into title (name, code,type) values ('FII PTO BAND','PATB11','FII');
insert into title (name, code,type) values ('FII RBR DES','RBRM11','FII');
insert into title (name, code,type) values ('FII RBRHGRAD','RBRR11','FII');
insert into title (name, code,type) values ('FII REC RECE','RECR11','FII');
insert into title (name, code,type) values ('FII REC REND','RECT11','FII');
insert into title (name, code,type) values ('FII SHOPJSUL','JRDM11','FII');
insert into title (name, code,type) values ('FII SHOP PDP','SHDP11','FII');
insert into title (name, code,type) values ('FII SIA CORP','SAIC11','FII');
insert into title (name, code,type) values ('FII TBOFFICE','TBOF11','FII');
insert into title (name, code,type) values ('FII TORRE AL','ALMI11','FII');
insert into title (name, code,type) values ('FII TORRE NO','TRNT11','FII');
insert into title (name, code,type) values ('FII OLIMPIA','VLOL11','FII');
insert into title (name, code,type) values ('FII NCH EQI','EQIN11','FII');
insert into title (name, code,type) values ('FII OURI FOF','OUFF11','FII');
insert into title (name, code,type) values ('FII WTC SP','WTSP11','FII');
insert into title (name, code,type) values ('FII V2 PROP','VVPR11','FII');
insert into title (name, code,type) values ('FII VBI LOG','LVBI11','FII');
insert into title (name, code,type) values ('FII BARIGUI','BARI11','FII');
insert into title (name, code,type) values ('FII BRHOTEIS','BRHT11','FII');
insert into title (name, code,type) values ('FII ABSOLUTO','BPFF11','FII');
insert into title (name, code,type) values ('FII B VAREJO','BVAR11','FII');
insert into title (name, code,type) values ('FII BTG SHOP','BPML11','FII');
insert into title (name, code,type) values ('FII BTG TAGR','BTRA11','FII');
insert into title (name, code,type) values ('FII CAIXA CI','CXCI11','FII');
insert into title (name, code,type) values ('FII CX CEDAE','CXCE11','FII');
insert into title (name, code,type) values ('FII CX TRX','CXTL11','FII');
insert into title (name, code,type) values ('FII C TEXTIL','CTXT11','FII');
insert into title (name, code,type) values ('FII CJ','CJFI11','FII');
insert into title (name, code,type) values ('FII S F LIMA','FLMA11','FII');
insert into title (name, code,type) values ('FII OURINVES','EDFO11','FII');
insert into title (name, code,type) values ('FII EUROPAR','EURO11','FII');
insert into title (name, code,type) values ('FII GEN SEV','GESE11','FII');
insert into title (name, code,type) values ('FII ABC IMOB','ABCP11','FII');
insert into title (name, code,type) values ('FII G TOWERS','GTWR11','FII');
insert into title (name, code,type) values ('FII HABITAT','HBTT11','FII');
insert into title (name, code,type) values ('FII UNIMED C','HUCG11','FII');
insert into title (name, code,type) values ('FII H UNIMED','HUSC11','FII');
insert into title (name, code,type) values ('FII INDL BR','FIIB11','FII');
insert into title (name, code,type) values ('FII INFRA RE','FINF11','FII');
insert into title (name, code,type) values ('FII MEMORIAL','FMOF11','FII');
insert into title (name, code,type) values ('FII MERC BR','MBRF11','FII');
insert into title (name, code,type) values ('FII MOGNO','MGFF11','FII');
insert into title (name, code,type) values ('FII MV9','MVFI11','FII');
insert into title (name, code,type) values ('FII NESTPAR','NPAR11','FII');
insert into title (name, code,type) values ('FII OURILOG','OULG11','FII');
insert into title (name, code,type) values ('FII PANAMBY','PABY11','FII');
insert into title (name, code,type) values ('FII P NEGRA','FPNG11','FII');
insert into title (name, code,type) values ('FII POLO II','ESTQ11','FII');
insert into title (name, code,type) values ('FII POLO SHO','VPSI11','FII');
insert into title (name, code,type) values ('FII A BRANCA','FPAB11','FII');
insert into title (name, code,type) values ('FII RBR PCRI','RBRY11','FII');
insert into title (name, code,type) values ('FII RBR PROP','RBRP11','FII');
insert into title (name, code,type) values ('FII RIOB RC','RCRB11','FII');
insert into title (name, code,type) values ('FII RIOB ED','RBED11','FII');
insert into title (name, code,type) values ('FII RIOB VA','RBVA11','FII');
insert into title (name, code,type) values ('FII RIONEGRO','RNGO11','FII');
insert into title (name, code,type) values ('FII SAO FER','SFND11','FII');
insert into title (name, code,type) values ('FII SC 401','FISC11','FII');
insert into title (name, code,type) values ('FII SCP','SCPF11','FII');
insert into title (name, code,type) values ('FII SDI LOG','SDIL11','FII');
insert into title (name, code,type) values ('FII HIGIENOP','SHPH11','FII');
insert into title (name, code,type) values ('FII TG ATIVO','TGAR11','FII');
insert into title (name, code,type) values ('FII THE ONE','ONEF11','FII');
insert into title (name, code,type) values ('FII VEREDA','VERE11','FII');
insert into title (name, code,type) values ('FII V PARQUE','FVPQ11','FII');
insert into title (name, code,type) values ('FII VIDANOVA','FIVN11','FII');
insert into title (name, code,type) values ('FII VOT LOG','VTLT11','FII');
insert into title (name, code,type) values ('FII VOT SEC','VSEC11','FII');
insert into title (name, code,type) values ('FII VOT SHOP','VSHO11','FII');
insert into title (name, code,type) values ('FII UNIDADES','IDFI11','FII');
insert into title (name, code,type) values ('FII FOF BREI','IBFF11','FII');
insert into title (name, code,type) values ('FII MOGNO ID','MGIM11','FII');
insert into title (name, code,type) values ('FII PLURAL R','PLCR11','FII');
insert into title (name, code,type) values ('FII PLUS','VTPL11','FII');
insert into title (name, code,type) values ('FII REC LOG','RELG11','FII');
insert into title (name, code,type) values ('FII VBI CRI','CVBI11','FII');
insert into title (name, code,type) values ('FII MAUA','MCCI11','FII');
insert into title (name, code,type) values ('FII GRPLMALL','FGPM11','FII');
insert into title (name, code,type) values ('FII A TOWN','ATWN11','FII');
insert into title (name, code,type) values ('FII ATRIO','ARRI11','FII');
insert into title (name, code,type) values ('FII BTG AGRO','BTAL11','FII');
insert into title (name, code,type) values ('FII CEF CORP','CXCO11','FII');
insert into title (name, code,type) values ('FII HOUSI','HOSI11','FII');
insert into title (name, code,type) values ('FII MOGNO HT','MGHT11','FII');
insert into title (name, code,type) values ('FII REC FOF','RECX11','FII');
insert into title (name, code,type) values ('FII VBI PRI','PVBI11','FII');
insert into title (name, code,type) values ('FII DEVA FOF','DVFF11','FII');
insert into title (name, code,type) values ('FII MOGNO HG','MGCR11','FII');
insert into title (name, code,type) values ('FII RB CFOF','RFOF11','FII');
insert into title (name, code,type) values ('FII VOTP V','VTPA11','FII');
insert into title (name, code,type) values ('FII VOTP XII','VTXI11','FII');
insert into title (name, code,type) values ('FII MULT REN','HBRH11','FII');
insert into title (name, code,type) values ('FII FED HY','FDHY11','FII');
insert into title (name, code,type) values ('FII IRIDIUM','IRDM11','FII');
insert into title (name, code,type) values ('FII SBCLOG','SBCL11','FII');
insert into title (name, code,type) values ('FII S VAREJO','SPVJ11','FII');
insert into title (name, code,type) values ('FII KINEAFOF','KFOF11','FII');
insert into title (name, code,type) values ('FII OU RENDA','OURE11','FII');
insert into title (name, code,type) values ('FII BLUE REC','BLUR11','FII');
insert into title (name, code,type) values ('FII DEV ONE','LKDV11','FII');
insert into title (name, code,type) values ('FII RBR III','RBRI11','FII');
insert into title (name, code,type) values ('FII ATHENA I','FATN11','FII');
insert into title (name, code,type) values ('FII BRLPROII','BRLA11','FII');
insert into title (name, code,type) values ('FII CAIXA AG','CXAG11','FII');
insert into title (name, code,type) values ('FII HBC REN','HBCR11','FII');
insert into title (name, code,type) values ('FII MINT EDU','MINT11','FII');
insert into title (name, code,type) values ('FII RIZA TX','RZTR11','FII');
insert into title (name, code,type) values ('FII ROOFTOPI','ROOF11','FII');
insert into title (name, code,type) values ('FII TOUR V','TCIN11','FII');
insert into title (name, code,type) values ('FII GALAPAGO','GCFF11','FII');
insert into title (name, code,type) values ('FII GLPG CRI','GCRI11','FII');
insert into title (name, code,type) values ('FII GAZIT','GZIT11','FII');
insert into title (name, code,type) values ('FII GENERAL','GSFI11','FII');
insert into title (name, code,type) values ('','11','FII');
insert into title (name, code,type) values ('FII GGRCOVEP','GGRC11','FII');
insert into title (name, code,type) values ('FII GLP LOG','GLPL11','FII');
insert into title (name, code,type) values ('FII GP RCFA','RCFA11','FII');
insert into title (name, code,type) values ('FII GTIS LG','GTLG11','FII');
insert into title (name, code,type) values ('FII GUARDIAN','GALG11','FII');
insert into title (name, code,type) values ('FII HABIT II','HABT11','FII');
insert into title (name, code,type) values ('FII HAZ','ATCR11','FII');
insert into title (name, code,type) values ('FII HECTARE','HCTR11','FII');
insert into title (name, code,type) values ('FII HECT DES','HCST11','FII');
insert into title (name, code,type) values ('FII HECT PRP','HCPR11','FII');
insert into title (name, code,type) values ('FII HECT CRI','HCHG11','FII');
insert into title (name, code,type) values ('FII HEDGEAAA','HAAA11','FII');
insert into title (name, code,type) values ('FII HATRIUM','ATSA11','FII');
insert into title (name, code,type) values ('FII HEDGEBS','HGBS11','FII');
insert into title (name, code,type) values ('FII HEDGELOG','HLOG11','FII');
insert into title (name, code,type) values ('FII HEDGE OF','HDOF11','FII');
insert into title (name, code,type) values ('FII HREALTY','HRDF11','FII');
insert into title (name, code,type) values ('FII HEDGEREC','HREC11','FII');
insert into title (name, code,type) values ('FII HEDGE SD','SEED11','FII');
insert into title (name, code,type) values ('FII HEDGEPDP','HPDP11','FII');
insert into title (name, code,type) values ('FII HTOPFOF3','HFOF11','FII');
insert into title (name, code,type) values ('FII HGI CRI','HGIC11','FII');
insert into title (name, code,type) values ('FII HSI CRI','HSAF11','FII');
insert into title (name, code,type) values ('FII HSI LOG','HSLG11','FII');
insert into title (name, code,type) values ('FII HSI MALL','HSML11','FII');
insert into title (name, code,type) values ('FII HSIRENDA','HSRE11','FII');
insert into title (name, code,type) values ('FII HUSI','HUSI11','FII');
insert into title (name, code,type) values ('FII INTER IP','ITIP11','FII');
insert into title (name, code,type) values ('FII INTER','BICR11','FII');
insert into title (name, code,type) values ('FII IRIM','IRIM11','FII');
insert into title (name, code,type) values ('FII JCDA I','JCDA11','FII');
insert into title (name, code,type) values ('FII JBFO FOF','JBFO11','FII');
insert into title (name, code,type) values ('FII JFDCAM','VJFD11','FII');
insert into title (name, code,type) values ('FII JFL LIV','JFLL11','FII');
insert into title (name, code,type) values ('FII JPPMOGNO','JPPA11','FII');
insert into title (name, code,type) values ('FII JPP CAPI','JPPC11','FII');
insert into title (name, code,type) values ('FII JS A FIN','JSAF11','FII');
insert into title (name, code,type) values ('FII JS REAL','JSRE11','FII');
insert into title (name, code,type) values ('FII JT PREV','JTPR11','FII');
insert into title (name, code,type) values ('FII KILIMA','KISU11','FII');
insert into title (name, code,type) values ('FII KIVO','KIVO11','FII');
insert into title (name, code,type) values ('FII KINEA CR','KCRE11','FII');
insert into title (name, code,type) values ('FII KINEA HY','KNHY11','FII');
insert into title (name, code,type) values ('FII KII REAL','KNRE11','FII');
insert into title (name, code,type) values ('FII KINEA IP','KNIP11','FII');
insert into title (name, code,type) values ('FII KINEA','KNRI11','FII');
insert into title (name, code,type) values ('FII KINEA RI','KNCR11','FII');
insert into title (name, code,type) values ('FII KINEA SC','KNSC11','FII');
insert into title (name, code,type) values ('FII LAGO PDR','LPLP11','FII');
insert into title (name, code,type) values ('FII LATERES','LATR11','FII');
insert into title (name, code,type) values ('FII LEGATUS','LASC11','FII');
insert into title (name, code,type) values ('FII LESTE PA','LSPA11','FII');
insert into title (name, code,type) values ('FII LOFT I','LOFT11','FII');
insert into title (name, code,type) values ('FII LOFT II','LFTT11','FII');
insert into title (name, code,type) values ('FII LGCP INT','LGCP11','FII');
insert into title (name, code,type) values ('FII LUGGO','LUGG11','FII');
insert into title (name, code,type) values ('FII MALLS BP','MALL11','FII');
insert into title (name, code,type) values ('FII MMVE OP','MMVE11','FII');
insert into title (name, code,type) values ('FII MAUA DES','MADS11','FII');
insert into title (name, code,type) values ('FII MAUA HF','MCHF11','FII');
insert into title (name, code,type) values ('FII MAXI REN','MXRF11','FII');
insert into title (name, code,type) values ('FII MERITO I','MFII11','FII');
insert into title (name, code,type) values ('FII MERITOFA','MFAI11','FII');
insert into title (name, code,type) values ('FII MOGNO LG','MGLG11','FII');
insert into title (name, code,type) values ('FII MOGNO PR','MGLC11','FII');
insert into title (name, code,type) values ('FII MORE ATV','MATV11','FII');
insert into title (name, code,type) values ('FII MORE RE','MORE11','FII');
insert into title (name, code,type) values ('FII MORE CRI','MORC11','FII');
insert into title (name, code,type) values ('FII MULTPROP','PRTS11','FII');
insert into title (name, code,type) values ('FII MULTSHOP','SHOP11','FII');
insert into title (name, code,type) values ('FII MTGESTAO','DRIT11','FII');
insert into title (name, code,type) values ('FII MULT OF2','MOFF11','FII');
insert into title (name, code,type) values ('FII NAVI TOT','NAVT11','FII');
insert into title (name, code,type) values ('FII NAVI RSD','APTO11','FII');
insert into title (name, code,type) values ('FII NEWPORT','NEWL11','FII');
insert into title (name, code,type) values ('FII NEWRU','NEWU11','FII');
insert into title (name, code,type) values ('FII NOVA I','NVIF11','FII');
insert into title (name, code,type) values ('FII OPPORTUN','FTCE11','FII');
insert into title (name, code,type) values ('FII OURI JPP','OUJP11','FII');
insert into title (name, code,type) values ('FII OURO PRT','ORPD11','FII');
insert into title (name, code,type) values ('FII PANORAMA','PNDL11','FII');
insert into title (name, code,type) values ('FII LASTMILE','PNLN11','FII');
insert into title (name, code,type) values ('FII PAN PROP','PNPR11','FII');
insert into title (name, code,type) values ('FII PARK PAR','VTVI11','FII');
insert into title (name, code,type) values ('FII PARQ ANH','PQAG11','FII');
insert into title (name, code,type) values ('FII PATRIA','PATC11','FII');
insert into title (name, code,type) values ('FII PATR LOG','PATL11','FII');
insert into title (name, code,type) values ('FII PERFORMA','PEMA11','FII');
insert into title (name, code,type) values ('FII PERSONAL','PRSN11','FII');
insert into title (name, code,type) values ('FII PLURAL L','PLOG11','FII');
insert into title (name, code,type) values ('FII PLUR URB','PURB11','FII');
insert into title (name, code,type) values ('FII POLO CRI','PORD11','FII');
insert into title (name, code,type) values ('FII POLO I','PLRI11','FII');
insert into title (name, code,type) values ('FII PRAZO','PRZS11','FII');
insert into title (name, code,type) values ('FII P VARGAS','PRSV11','FII');
insert into title (name, code,type) values ('FII PROLOGIS','PBLV11','FII');
insert into title (name, code,type) values ('FII QUASAR A','QAGR11','FII');
insert into title (name, code,type) values ('FII QUASAR C','QAMI11','FII');
insert into title (name, code,type) values ('FII QUATA','QIRI11','FII');
insert into title (name, code,type) values ('FII RCAP FOF','XBXO11','FII');
insert into title (name, code,type) values ('FII RBRESID3','RSPD11','FII');
insert into title (name, code,type) values ('FII RBRESID2','RBDS11','FII');
insert into title (name, code,type) values ('FII RBRES IV','RBIR11','FII');
insert into title (name, code,type) values ('FII RBCAP LG','RBLG11','FII');
insert into title (name, code,type) values ('FII R INCOME','RBCO11','FII');
insert into title (name, code,type) values ('FII RBCAP RI','RRCI11','FII');
insert into title (name, code,type) values ('FII RB CAP I','FIIP11','FII');
insert into title (name, code,type) values ('FII RB II','RBRD11','FII');
insert into title (name, code,type) values ('FII RB REN','RBRU11','FII');
insert into title (name, code,type) values ('FII RB TFO','RBTS11','FII');
insert into title (name, code,type) values ('FII RBRALPHA','RBRF11','FII');
insert into title (name, code,type) values ('FII RBR FEED','RCFF11','FII');
insert into title (name, code,type) values ('FII RBR LOG','RBRL11','FII');
insert into title (name, code,type) values ('FII RBR PR','RPRI11','FII');
insert into title (name, code,type) values ('FII REAGMULT','RMAI11','FII');
insert into title (name, code,type) values ('FII RBCRI IV','RBHG11','FII');
insert into title (name, code,type) values ('FII RB YIELD','RBHY11','FII');
insert into title (name, code,type) values ('FII RIOBCRI2','RBVO11','FII');
insert into title (name, code,type) values ('FII RIOB FF','RBFF11','FII');
insert into title (name, code,type) values ('FII RIOB RR','RBRS11','FII');
insert into title (name, code,type) values ('FII RIZA AKN','RZAK11','FII');
insert into title (name, code,type) values ('FII ARCTIUM','ARCT11','FII');
insert into title (name, code,type) values ('FII SANT PAP','SADI11','FII');
insert into title (name, code,type) values ('FII SANT REN','SARE11','FII');
insert into title (name, code,type) values ('FII S CARLOS','SACL11','FII');
insert into title (name, code,type) values ('FII DOMINGOS','FISD11','FII');
insert into title (name, code,type) values ('FII SAO FRAN','SFRO11','FII');
insert into title (name, code,type) values ('FII SEQUOIA','SEQR11','FII');
insert into title (name, code,type) values ('FII SERRA VD','SRVD11','FII');
insert into title (name, code,type) values ('FII W PLAZA','WPLZ11','FII');
insert into title (name, code,type) values ('FII SIG CAP','SIGR11','FII');
insert into title (name, code,type) values ('FII REIT RIV','REIT11','FII');
insert into title (name, code,type) values ('FII SJ AU','SJAU11','FII');
insert into title (name, code,type) values ('FII SOLARIUM','SOLR11','FII');
insert into title (name, code,type) values ('FII SP DOWNT','SPTW11','FII');
insert into title (name, code,type) values ('FII SPA','SPAF11','FII');
insert into title (name, code,type) values ('FII STARX','STRX11','FII');
insert into title (name, code,type) values ('FII SUNOFOFI','SNFF11','FII');
insert into title (name, code,type) values ('FII SUNO CRI','SNCI11','FII');
insert into title (name, code,type) values ('FII TELLUS','TELD11','FII');
insert into title (name, code,type) values ('FII TELF','TELF11','FII');
insert into title (name, code,type) values ('FII TEL PROP','TEPP11','FII');
insert into title (name, code,type) values ('FII TISHMAN','TSER11','FII');
insert into title (name, code,type) values ('FII TJK REND','TJKB11','FII');
insert into title (name, code,type) values ('FII TORDE EI','TORD11','FII');
insert into title (name, code,type) values ('FII TRANSINC','TSNC11','FII');
insert into title (name, code,type) values ('FII TREECORP','TCPF11','FII');
insert into title (name, code,type) values ('FII TRXE COR','XTED11','FII');
insert into title (name, code,type) values ('FII TRX REAL','TRXF11','FII');
insert into title (name, code,type) values ('FII TRX R II','TRXB11','FII');
insert into title (name, code,type) values ('FII TS NEW','TSNM11','FII');
insert into title (name, code,type) values ('FII URCA REN','URPR11','FII');
insert into title (name, code,type) values ('FII VALREIII','VGIR11','FII');
insert into title (name, code,type) values ('FII VALORAIP','VGIP11','FII');
insert into title (name, code,type) values ('FII VALOR HE','VGHF11','FII');
insert into title (name, code,type) values ('FII VBI CON','EVBI11','FII');
insert into title (name, code,type) values ('FII VBI REIT','RVBI11','FII');
insert into title (name, code,type) values ('FII VECTIS','VCJR11','FII');
insert into title (name, code,type) values ('FII VECT REN','VCRR11','FII');
insert into title (name, code,type) values ('FII VQ LAJES','VLJS11','FII');
insert into title (name, code,type) values ('FII VENUS','SALI11','FII');
insert into title (name, code,type) values ('FII VERS CRI','VSLH11','FII');
insert into title (name, code,type) values ('FII VIC DES','VIDS11','FII');
insert into title (name, code,type) values ('FII VINCI IU','VIUR11','FII');
insert into title (name, code,type) values ('FII VINCI IF','VIFI11','FII');
insert into title (name, code,type) values ('FII VINCI LG','VILG11','FII');
insert into title (name, code,type) values ('FII VINCI OF','VINO11','FII');
insert into title (name, code,type) values ('FII VINCI SC','VISC11','FII');
insert into title (name, code,type) values ('FII V MASTER','VOTS11','FII');
insert into title (name, code,type) values ('FII VX XVI','VXXV11','FII');
insert into title (name, code,type) values ('FII WHG REAL','WHGR11','FII');
insert into title (name, code,type) values ('FII XP MACAE','XPCM11','FII');
insert into title (name, code,type) values ('FII XP CRED','XPCI11','FII');
insert into title (name, code,type) values ('FII XP HOT','XPHT11','FII');
insert into title (name, code,type) values ('FII XP INDL','XPIN11','FII');
insert into title (name, code,type) values ('FII XP LOG','XPLG11','FII');
insert into title (name, code,type) values ('FII XP MALLS','XPML11','FII');
insert into title (name, code,type) values ('FII XP PROP','XPPR11','FII');
insert into title (name, code,type) values ('FII XP SELEC','XPSF11','FII');
insert into title (name, code,type) values ('FII YUCA','YUFI11','FII');
insert into title (name, code,type) values ('FII ZION','ZIFI11','FII');
