CREATE TABLE title (
	id INT NOT NULL AUTO_INCREMENT,
	name varchar(255) NOT NULL,
	code VARCHAR(20) NOT NULL,
	PRIMARY KEY ( id )
);

insert into title (name, code) values ('3R PETROLEUM ON','RRRP3');
insert into title (name, code) values ('3TENTOS ON','TTEN3');
insert into title (name, code) values ('ABC BRASIL PN','ABCB4');
insert into title (name, code) values ('ADOBE INC DRN','ADBE34');
insert into title (name, code) values ('ADVANCED MIC DRN','A1MD34');
insert into title (name, code) values ('AERIS ON','AERI3');
insert into title (name, code) values ('AES BRASIL ON','AESB3');
insert into title (name, code) values ('AES TIETE E UNT','TIET11');
insert into title (name, code) values ('AGROGALAXY ON','AGXY3');
insert into title (name, code) values ('AIRBNB DRN','AIRB34');
insert into title (name, code) values ('ALIANSCSONAE ON','ALSO3');
insert into title (name, code) values ('ALIBABAGR DRN','BABA34');
insert into title (name, code) values ('ALLIAR ON','AALR3');
insert into title (name, code) values ('ALLIED ON','ALLD3');
insert into title (name, code) values ('ALPARGATAS PN','ALPA4');
insert into title (name, code) values ('ALPHABET DRN A','GOGL34');
insert into title (name, code) values ('ALUPAR UNT','ALUP11');
insert into title (name, code) values ('AMAZON DRN','AMZO34');
insert into title (name, code) values ('AMBEV S/A ON','ABEV3');
insert into title (name, code) values ('AMBIPAR ON','AMBP3');
insert into title (name, code) values ('AMERICAN AIR DRN','AALL34');
insert into title (name, code) values ('AMERICANAS ON','AMER3');
insert into title (name, code) values ('ANIMA ON','ANIM3');
insert into title (name, code) values ('APPLE DRN','AAPL34');
insert into title (name, code) values ('AREZZO CO ON','ARZZ3');
insert into title (name, code) values ('ARMAC ON','ARML3');
insert into title (name, code) values ('ASSAI ON','ASAI3');
insert into title (name, code) values ('AURA 360 DR3','AURA33');
insert into title (name, code) values ('AZUL PN','AZUL4');
insert into title (name, code) values ('B3 ON','B3SA3');
insert into title (name, code) values ('BANCO BMG PN','BMGB4');
insert into title (name, code) values ('BANCO INTER ON EJ','BIDI3');
insert into title (name, code) values ('BANCO INTER PN EJ','BIDI4');
insert into title (name, code) values ('BANCO INTER UNT EJ','BIDI11');
insert into title (name, code) values ('BANCO PAN PN','BPAN4');
insert into title (name, code) values ('BANK AMERICA DRN ED','BOAC34');
insert into title (name, code) values ('BANRISUL PNB','BRSR6');
insert into title (name, code) values ('BBSEGURIDADE ON','BBSE3');
insert into title (name, code) values ('BEMOBI TECH ON','BMOB3');
insert into title (name, code) values ('BERKSHIRE DRN','BERK34');
insert into title (name, code) values ('BIONTECH SE DRN','B1NT34');
insert into title (name, code) values ('BITCOIN HASH CI','BITH11');
insert into title (name, code) values ('BK BRASIL ON','BKBR3');
insert into title (name, code) values ('BLAU ON','BLAU3');
insert into title (name, code) values ('BOA SAFRA ON','SOJA3');
insert into title (name, code) values ('BOA VISTA ON','BOAS3');
insert into title (name, code) values ('BOOKING DRN','BKNG34');
insert into title (name, code) values ('BR BROKERS ON','BBRK3');
insert into title (name, code) values ('BR MALLS PAR ON','BRML3');
insert into title (name, code) values ('BR PARTNERS UNT','BRBI11');
insert into title (name, code) values ('BR PROPERT ON','BRPR3');
insert into title (name, code) values ('BRADESCO ON EJ','BBDC3');
insert into title (name, code) values ('BRADESCO PN EJ','BBDC4');
insert into title (name, code) values ('BRADESPAR ON','BRAP3');
insert into title (name, code) values ('BRADESPAR PN','BRAP4');
insert into title (name, code) values ('BRASIL ON EX','BBAS3');
insert into title (name, code) values ('BRASILAGRO ON','AGRO3');
insert into title (name, code) values ('BRASKEM PNA','BRKM5');
insert into title (name, code) values ('BRF SA ON','BRFS3');
insert into title (name, code) values ('BRISANET ON','BRIT3');
insert into title (name, code) values ('BTGP BANCO UNT','BPAC11');
insert into title (name, code) values ('CAIXA SEGURI ON','CXSE3');
insert into title (name, code) values ('CAMIL ON EJ','CAML3');
insert into title (name, code) values ('CARREFOUR BR ON','CRFB3');
insert into title (name, code) values ('CBA ON','CBAV3');
insert into title (name, code) values ('CCR SA ON','CCRO3');
insert into title (name, code) values ('CEA MODAS ON','CEAB3');
insert into title (name, code) values ('CEMIG ON','CMIG3');
insert into title (name, code) values ('CEMIG PN','CMIG4');
insert into title (name, code) values ('CESP PNB','CESP6');
insert into title (name, code) values ('CHEVRON DRN','CHVX34');
insert into title (name, code) values ('CIELO ON','CIEL3');
insert into title (name, code) values ('CLEARSALE ON','CLSA3');
insert into title (name, code) values ('COCA COLA DRN','COCA34');
insert into title (name, code) values ('COGNA ON ON','COGN3');
insert into title (name, code) values ('COMCAST DRN','CMCS34');
insert into title (name, code) values ('COPASA ON','CSMG3');
insert into title (name, code) values ('COPEL ON','CPLE3');
insert into title (name, code) values ('COPEL PNB','CPLE6');
insert into title (name, code) values ('COPEL UNT','CPLE11');
insert into title (name, code) values ('COREMSCI EUR DRN','BIEU39');
insert into title (name, code) values ('COSAN ON','CSAN3');
insert into title (name, code) values ('COSTCO DRN','COWC34');
insert into title (name, code) values ('CPFL ENERGIA ON','CPFE3');
insert into title (name, code) values ('CRUZEIRO EDU ON','CSED3');
insert into title (name, code) values ('CSNMINERACAO ON','CMIN3');
insert into title (name, code) values ('CSU CARDSYST ON','CARD3');
insert into title (name, code) values ('CURY S/A ON','CURY3');
insert into title (name, code) values ('CVC BRASIL ON','CVCB3');
insert into title (name, code) values ('CYRELA REALT ON','CYRE3');
insert into title (name, code) values ('DASA ON','DASA3');
insert into title (name, code) values ('DESKTOP ON','DESK3');
insert into title (name, code) values ('DEXCO ON','DXCO3');
insert into title (name, code) values ('DEXXOS PAR ON','DEXP3');
insert into title (name, code) values ('DIMED ON','PNVL3');
insert into title (name, code) values ('DIRECIONAL ON','DIRR3');
insert into title (name, code) values ('DOMMO ON','DMMO3');
insert into title (name, code) values ('ECORODOVIAS ON','ECOR3');
insert into title (name, code) values ('ELETROBRAS ON','ELET3');
insert into title (name, code) values ('ELETROBRAS PNB','ELET6');
insert into title (name, code) values ('ELETROMIDIA ON','ELMD3');
insert into title (name, code) values ('EMBRAER ON','EMBR3');
insert into title (name, code) values ('ENAUTA PART ON','ENAT3');
insert into title (name, code) values ('ENERGIAS BR ON','ENBR3');
insert into title (name, code) values ('ENERGISA UNT','ENGI11');
insert into title (name, code) values ('ENEVA ON','ENEV3');
insert into title (name, code) values ('ENGIE BRASIL ON','EGIE3');
insert into title (name, code) values ('ENJOEI ON','ENJU3');
insert into title (name, code) values ('EQUATORIAL ON','EQTL3');
insert into title (name, code) values ('ESPACOLASER ON','ESPA3');
insert into title (name, code) values ('ETERNIT ON','ETER3');
insert into title (name, code) values ('ETF BRA IBOV CI','BOVB11');
insert into title (name, code) values ('ETHER HASH CI','ETHE11');
insert into title (name, code) values ('EVEN ON','EVEN3');
insert into title (name, code) values ('EXXON MOBIL DRN','EXXO34');
insert into title (name, code) values ('EZTEC ON','EZTC3');
insert into title (name, code) values ('FER HERINGER ON','FHER3');
insert into title (name, code) values ('FERBASA PN','FESA4');
insert into title (name, code) values ('FIAGRO RIZA CI ER','RZAG11');
insert into title (name, code) values ('FII ALIANZA CI','ALZR11');
insert into title (name, code) values ('FII ARCTIUM CI','ARCT11');
insert into title (name, code) values ('FII BARIGUI CI ER','BARI11');
insert into title (name, code) values ('FII BB PRGII CI ER','BBPO11');
insert into title (name, code) values ('FII BC FFII CI ER','BCFF11');
insert into title (name, code) values ('FII BC FUND CI ER','BRCR11');
insert into title (name, code) values ('FII BEES CRI CI ER','BCRI11');
insert into title (name, code) values ('FII BRESCO CI ER','BRCO11');
insert into title (name, code) values ('FII BTLG CI ES','BTLG11');
insert into title (name, code) values ('FII CAP REIT CI ER','CPFF11');
insert into title (name, code) values ('FII CAPI SEC CI','CPTS11');
insert into title (name, code) values ('FII CSHG CRI CI ER','HGCR11');
insert into title (name, code) values ('FII CSHG LOG CI ER','HGLG11');
insert into title (name, code) values ('FII CSHG URB CI ER','HGRU11');
insert into title (name, code) values ('FII DEVANT CI ER','DEVA11');
insert into title (name, code) values ('FII EXCELLEN CI ER','FEXC11');
insert into title (name, code) values ('FII FATOR VE CI ER','VRTA11');
insert into title (name, code) values ('FII GGRCOVEP CI ER','GGRC11');
insert into title (name, code) values ('FII HABIT II CI ER','HABT11');
insert into title (name, code) values ('FII HECTARE CI ER','HCTR11');
insert into title (name, code) values ('FII HEDGEBS CI ER','HGBS11');
insert into title (name, code) values ('FII HG REAL CI ER','HGRE11');
insert into title (name, code) values ('FII HSI MALL CI ER','HSML11');
insert into title (name, code) values ('FII HTOPFOF3 CI ER','HFOF11');
insert into title (name, code) values ('FII IRIDIUM CI ER','IRDM11');
insert into title (name, code) values ('FII JS REAL CI ER','JSRE11');
insert into title (name, code) values ('FII KINEA CI ER','KNRI11');
insert into title (name, code) values ('FII KINEA HY CI ER','KNHY11');
insert into title (name, code) values ('FII KINEA IP CI ER','KNIP11');
insert into title (name, code) values ('FII KINEA RI CI ER','KNCR11');
insert into title (name, code) values ('FII KINEA SC CI ER','KNSC11');
insert into title (name, code) values ('FII MALLS BP CI ER','MALL11');
insert into title (name, code) values ('FII MAUA CI','MCCI11');
insert into title (name, code) values ('FII MAXI REN CI ER','MXRF11');
insert into title (name, code) values ('FII RBR PROP CI ER','RBRP11');
insert into title (name, code) values ('FII RBRALPHA CI ER','RBRF11');
insert into title (name, code) values ('FII RBRHGRAD CI ER','RBRR11');
insert into title (name, code) values ('FII REC RECE CI ER','RECR11');
insert into title (name, code) values ('FII RIZA AKN CI','RZAK11');
insert into title (name, code) values ('FII RIZA TX CI ER','RZTR11');
insert into title (name, code) values ('FII SUNO CRI CI','SNCI11');
insert into title (name, code) values ('FII TG ATIVO CI ER','TGAR11');
insert into title (name, code) values ('FII TRX REAL CI ER','TRXF11');
insert into title (name, code) values ('FII URCA REN CI ER','URPR11');
insert into title (name, code) values ('FII VALOR HE CI ER','VGHF11');
insert into title (name, code) values ('FII VALORAIP CI','VGIP11');
insert into title (name, code) values ('FII VALREIII CI','VGIR11');
insert into title (name, code) values ('FII VBI CRI CI ER','CVBI11');
insert into title (name, code) values ('FII VBI LOG CI ER','LVBI11');
insert into title (name, code) values ('FII VBI PRI CI ER','PVBI11');
insert into title (name, code) values ('FII VECTIS CI ER','VCJR11');
insert into title (name, code) values ('FII VINCI LG CI ER','VILG11');
insert into title (name, code) values ('FII VINCI OF CI ER','VINO11');
insert into title (name, code) values ('FII VINCI SC CI ER','VISC11');
insert into title (name, code) values ('FII XP CRED CI ER','XPCI11');
insert into title (name, code) values ('FII XP LOG CI ER','XPLG11');
insert into title (name, code) values ('FII XP MALLS CI','XPML11');
insert into title (name, code) values ('FII XP PROP CI ER','XPPR11');
insert into title (name, code) values ('FINAM CI *','FNAM11');
insert into title (name, code) values ('FINOR CI *','FNOR11');
insert into title (name, code) values ('FLEURY ON','FLRY3');
insert into title (name, code) values ('FOCUS ON ON','POWE3');
insert into title (name, code) values ('FRAS-LE ON','FRAS3');
insert into title (name, code) values ('GAFISA ON','GFSA3');
insert into title (name, code) values ('GENERAL MOT DRN','GMCO34');
insert into title (name, code) values ('GERDAU ON ED','GGBR3');
insert into title (name, code) values ('GERDAU PN ED','GGBR4');
insert into title (name, code) values ('GERDAU MET ON ED','GOAU3');
insert into title (name, code) values ('GERDAU MET PN ED','GOAU4');
insert into title (name, code) values ('GETNET BR UNT','GETT11');
insert into title (name, code) values ('GETNINJAS ON','NINJ3');
insert into title (name, code) values ('GOL PN','GOLL4');
insert into title (name, code) values ('GOLD TRUST DRN','BIAU39');
insert into title (name, code) values ('GPS ON','GGPS3');
insert into title (name, code) values ('GRENDENE ON','GRND3');
insert into title (name, code) values ('GRUPO MATEUS ON','GMAT3');
insert into title (name, code) values ('GRUPO NATURA ON','NTCO3');
insert into title (name, code) values ('GRUPO SBF ON','SBFG3');
insert into title (name, code) values ('GRUPO SOMA ON','SOMA3');
insert into title (name, code) values ('GUARARAPES ON','GUAR3');
insert into title (name, code) values ('HAPVIDA ON','HAPV3');
insert into title (name, code) values ('HASHDEX NCI CI','HASH11');
insert into title (name, code) values ('HELBOR ON','HBOR3');
insert into title (name, code) values ('HIDROVIAS ON','HBSA3');
insert into title (name, code) values ('HOME DEPOT DRN ED','HOME34');
insert into title (name, code) values ('HYPERA ON','HYPE3');
insert into title (name, code) values ('IGUATEMI S.A ON','IGTI3');
insert into title (name, code) values ('IGUATEMI S.A UNT','IGTI11');
insert into title (name, code) values ('IHPARDINI ON','PARD3');
insert into title (name, code) values ('IMC S/A ON','MEAL3');
insert into title (name, code) values ('INDS ROMI ON','ROMI3');
insert into title (name, code) values ('INEPAR ON','INEP3');
insert into title (name, code) values ('INFRACOMM ON','IFCM3');
insert into title (name, code) values ('INTELBRAS ON ED','INTB3');
insert into title (name, code) values ('INVESTO JOGO CI','JOGO11');
insert into title (name, code) values ('IOCHP-MAXION ON','MYPK3');
insert into title (name, code) values ('IRANI ON ED','RANI3');
insert into title (name, code) values ('IRBBRASIL RE ON','IRBR3');
insert into title (name, code) values ('ISHARE SP500 CI','IVVB11');
insert into title (name, code) values ('ISHARES BOVA CI','BOVA11');
insert into title (name, code) values ('ISHARES SMAL CI','SMAL11');
insert into title (name, code) values ('IT NOW IBOV CI','BOVV11');
insert into title (name, code) values ('IT NOW IDIV CI','DIVO11');
insert into title (name, code) values ('IT NOW IFNC CI','FIND11');
insert into title (name, code) values ('IT NOW IMA-B F11','IMAB11');
insert into title (name, code) values ('IT NOW IMAT CI','MATB11');
insert into title (name, code) values ('IT NOW PIBB CI','PIBB11');
insert into title (name, code) values ('IT NOW SMALL CI','SMAC11');
insert into title (name, code) values ('IT NOW SPXI CI','SPXI11');
insert into title (name, code) values ('ITAUSA ON','ITSA3');
insert into title (name, code) values ('ITAUSA PN','ITSA4');
insert into title (name, code) values ('ITAUUNIBANCO ON EJ','ITUB3');
insert into title (name, code) values ('ITAUUNIBANCO PN EJ','ITUB4');
insert into title (name, code) values ('JALLESMACHAD ON','JALL3');
insert into title (name, code) values ('JBS ON','JBSS3');
insert into title (name, code) values ('JHSF PART ON ED','JHSF3');
insert into title (name, code) values ('JOHNSON DRN','JNJB34');
insert into title (name, code) values ('JPMORGAN DRN','JPMC34');
insert into title (name, code) values ('JSL ON','JSLG3');
insert into title (name, code) values ('KEPLER WEBER ON','KEPL3');
insert into title (name, code) values ('KINEA INFRAF FIDCER','KDIF11');
insert into title (name, code) values ('KLABIN S/A PN','KLBN4');
insert into title (name, code) values ('KLABIN S/A UNT','KLBN11');
insert into title (name, code) values ('LAVVI ON','LAVV3');
insert into title (name, code) values ('LIGHT S/A ON','LIGT3');
insert into title (name, code) values ('LOCALIZA ON','RENT3');
insert into title (name, code) values ('LOCAMERICA ON','LCAM3');
insert into title (name, code) values ('LOCAWEB ON','LWSA3');
insert into title (name, code) values ('LOG COM PROP ON','LOGG3');
insert into title (name, code) values ('LOG-IN ON','LOGN3');
insert into title (name, code) values ('LOJAS MARISA ON','AMAR3');
insert into title (name, code) values ('LOJAS RENNER ON','LREN3');
insert into title (name, code) values ('LOPES BRASIL ON','LPSB3');
insert into title (name, code) values ('LUPATECH ON','LUPA3');
insert into title (name, code) values ('M.DIASBRANCO ON','MDIA3');
insert into title (name, code) values ('MAGAZ LUIZA ON','MGLU3');
insert into title (name, code) values ('MARCOPOLO PN','POMO4');
insert into title (name, code) values ('MARFRIG ON','MRFG3');
insert into title (name, code) values ('MASTERCARD DRN','MSCD34');
insert into title (name, code) values ('MATER DEI ON','MATD3');
insert into title (name, code) values ('MCDONALDS DRN','MCDC34');
insert into title (name, code) values ('MELIUZ ON','CASH3');
insert into title (name, code) values ('MELNICK ON','MELK3');
insert into title (name, code) values ('MERCADOLIBRE DRN','MELI34');
insert into title (name, code) values ('META PLAT DRN','FBOK34');
insert into title (name, code) values ('METAL LEVE ON','LEVE3');
insert into title (name, code) values ('MICRON TECHN DRN','MUTC34');
insert into title (name, code) values ('MICROSOFT DRN','MSFT34');
insert into title (name, code) values ('MILLS ON','MILS3');
insert into title (name, code) values ('MINERVA ON','BEEF3');
insert into title (name, code) values ('MITRE REALTY ON ED','MTRE3');
insert into title (name, code) values ('MOBLY ON','MBLY3');
insert into title (name, code) values ('MODALMAIS UNT','MODL11');
insert into title (name, code) values ('MODERNA INC DRN','M1RN34');
insert into title (name, code) values ('MOSAICO ON','MOSI3');
insert into title (name, code) values ('MOURA DUBEUX ON','MDNE3');
insert into title (name, code) values ('MOVIDA ON','MOVI3');
insert into title (name, code) values ('MRV ON','MRVE3');
insert into title (name, code) values ('MSCI ACWI DRN','BACW39');
insert into title (name, code) values ('MULTILASER ON','MLAS3');
insert into title (name, code) values ('MULTIPLAN ON','MULT3');
insert into title (name, code) values ('NEOENERGIA ON','NEOE3');
insert into title (name, code) values ('NEOGRID ON','NGRD3');
insert into title (name, code) values ('NETFLIX DRN','NFLX34');
insert into title (name, code) values ('NIKE DRN ED','NIKE34');
insert into title (name, code) values ('NU-NUBANK DR3','NUBR33');
insert into title (name, code) values ('NVIDIA CORP DRN ED','NVDC34');
insert into title (name, code) values ('OCCIDENT PTR DRN ED','OXYP34');
insert into title (name, code) values ('OCEANPACT ON','OPCT3');
insert into title (name, code) values ('ODONTOPREV ON','ODPV3');
insert into title (name, code) values ('OI ON ES','OIBR3');
insert into title (name, code) values ('OI PN ES','OIBR4');
insert into title (name, code) values ('OMEGAENERGIA ON','MEGA3');
insert into title (name, code) values ('ONCOCLINICAS ON','ONCO3');
insert into title (name, code) values ('ORIZON ON','ORVR3');
insert into title (name, code) values ('P.ACUCAR-CBD ON','PCAR3');
insert into title (name, code) values ('PAGUE MENOS ON','PGMN3');
insert into title (name, code) values ('PARANAPANEMA ON','PMAM3');
insert into title (name, code) values ('PAYPAL HOLD DRN','PYPL34');
insert into title (name, code) values ('PETROBRAS ON','PETR3');
insert into title (name, code) values ('PETROBRAS PN','PETR4');
insert into title (name, code) values ('PETRORECSA ON','RECV3');
insert into title (name, code) values ('PETRORIO ON','PRIO3');
insert into title (name, code) values ('PETZ ON','PETZ3');
insert into title (name, code) values ('PFIZER DRN','PFIZ34');
insert into title (name, code) values ('PG DRN','PGCO34');
insert into title (name, code) values ('PLANOEPLANO ON','PLPL3');
insert into title (name, code) values ('PORTO SEGURO ON','PSSA3');
insert into title (name, code) values ('PORTOBELLO ON','PTBL3');
insert into title (name, code) values ('POSITIVO TEC ON','POSI3');
insert into title (name, code) values ('QR BITCOIN CI','QBTC11');
insert into title (name, code) values ('QR ETHER CI','QETH11');
insert into title (name, code) values ('QUALICORP ON','QUAL3');
insert into title (name, code) values ('QUERO-QUERO ON','LJQQ3');
insert into title (name, code) values ('RAIADROGASIL ON','RADL3');
insert into title (name, code) values ('RAIZEN PN','RAIZ4');
insert into title (name, code) values ('RANDON PART PN','RAPT4');
insert into title (name, code) values ('RECRUSUL ON','RCSL3');
insert into title (name, code) values ('REDE D OR ON','RDOR3');
insert into title (name, code) values ('RUMO S.A. ON','RAIL3');
insert into title (name, code) values ('SABESP ON','SBSP3');
insert into title (name, code) values ('SALESFORCE DRN','SSFO34');
insert into title (name, code) values ('SANEPAR ON','SAPR3');
insert into title (name, code) values ('SANEPAR PN','SAPR4');
insert into title (name, code) values ('SANEPAR UNT','SAPR11');
insert into title (name, code) values ('SANTANDER BR ON','SANB3');
insert into title (name, code) values ('SANTANDER BR PN','SANB4');
insert into title (name, code) values ('SANTANDER BR UNT','SANB11');
insert into title (name, code) values ('SANTOS BRP ON','STBP3');
insert into title (name, code) values ('SAO MARTINHO ON','SMTO3');
insert into title (name, code) values ('SCHULZ PN','SHUL4');
insert into title (name, code) values ('SEQUOIA LOG ON','SEQL3');
insert into title (name, code) values ('SER EDUCA ON','SEER3');
insert into title (name, code) values ('SID NACIONAL ON','CSNA3');
insert into title (name, code) values ('SIMPAR ON','SIMH3');
insert into title (name, code) values ('SINQIA ON','SQIA3');
insert into title (name, code) values ('SLC AGRICOLA ON','SLCE3');
insert into title (name, code) values ('SMART FIT ON','SMFT3');
insert into title (name, code) values ('SP500 VALUE DRN','BIVE39');
insert into title (name, code) values ('SUL AMERICA UNT','SULA11');
insert into title (name, code) values ('SUZANO S.A. ON','SUZB3');
insert into title (name, code) values ('SYN PROP TEC ON','SYNE3');
insert into title (name, code) values ('TAESA ON','TAEE3');
insert into title (name, code) values ('TAESA PN','TAEE4');
insert into title (name, code) values ('TAESA UNT','TAEE11');
insert into title (name, code) values ('TAIWANSMFAC DRN','TSMC34');
insert into title (name, code) values ('TAURUS ARMAS PN','TASA4');
insert into title (name, code) values ('TC ON','TRAD3');
insert into title (name, code) values ('TECHNOS ON','TECN3');
insert into title (name, code) values ('TECNISA ON','TCSA3');
insert into title (name, code) values ('TEGMA ON','TGMA3');
insert into title (name, code) values ('TELEF BRASIL ON EJ','VIVT3');
insert into title (name, code) values ('TENDA ON','TEND3');
insert into title (name, code) values ('TESLA INC DRN','TSLA34');
insert into title (name, code) values ('TIM ON','TIMS3');
insert into title (name, code) values ('TIME FOR FUN ON','SHOW3');
insert into title (name, code) values ('TOTVS ON','TOTS3');
insert into title (name, code) values ('TRAN PAULIST PN','TRPL4');
insert into title (name, code) values ('TREND ACWI CI','ACWI11');
insert into title (name, code) values ('TREND CHINA CI','XINA11');
insert into title (name, code) values ('TREND ESG D CI','ESGD11');
insert into title (name, code) values ('TREND ESG US CI','ESGU11');
insert into title (name, code) values ('TREND EUROPA CI','EURP11');
insert into title (name, code) values ('TREND IBOVX CI','BOVX11');
insert into title (name, code) values ('TREND NASDAQ CI','NASD11');
insert into title (name, code) values ('TREND OURO CI','GOLD11');
insert into title (name, code) values ('TREND US LRG CI','USAL11');
insert into title (name, code) values ('TRISUL ON','TRIS3');
insert into title (name, code) values ('TRUSTMSCI US DRN','BEGU39');
insert into title (name, code) values ('TUPY ON','TUPY3');
insert into title (name, code) values ('UBER TECH IN DRN','U1BE34');
insert into title (name, code) values ('ULTRAPAR ON ED','UGPA3');
insert into title (name, code) values ('UNIFIQUE ON','FIQE3');
insert into title (name, code) values ('UNIPAR ON','UNIP3');
insert into title (name, code) values ('UNIPAR PNB','UNIP6');
insert into title (name, code) values ('UNITEDHEALTH DRN ED','UNHH34');
insert into title (name, code) values ('USIMINAS ON','USIM3');
insert into title (name, code) values ('USIMINAS PNA','USIM5');
insert into title (name, code) values ('VALE ON ED','VALE3');
insert into title (name, code) values ('VALID ON','VLID3');
insert into title (name, code) values ('VAMOS ON','VAMO3');
insert into title (name, code) values ('VIA ON','VIIA3');
insert into title (name, code) values ('VIBRA ON','VBBR3');
insert into title (name, code) values ('VISA INC DRN','VISA34');
insert into title (name, code) values ('VITTIA ON','VITT3');
insert into title (name, code) values ('VIVARA S.A. ON','VIVA3');
insert into title (name, code) values ('VIVEO ON','VVEO3');
insert into title (name, code) values ('VIVER ON','VIVR3');
insert into title (name, code) values ('VULCABRAS ON','VULC3');
insert into title (name, code) values ('WALT DISNEY DRN','DISB34');
insert into title (name, code) values ('WDC NETWORKS ON','LVTC3');
insert into title (name, code) values ('WEG ON','WEGE3');
insert into title (name, code) values ('WELLS FARGO DRN','WFCO34');
insert into title (name, code) values ('WESTWING ON','WEST3');
insert into title (name, code) values ('WILSON SONS ON','PORT3');
insert into title (name, code) values ('WIZ S.A. ON','WIZS3');
insert into title (name, code) values ('XP INC DR1','XPBR31');
insert into title (name, code) values ('YDUQS PART ON','YDUQ3');
